Repository sony/nnabla, pull requests merged in 2019-12, with the labels that each got.

#551 BatchNorm backward in test mode
  include/nbla/function/batch_normalization.hpp
  include/nbla/imperative.hpp
  python/test/function/test_batch_normalization.py
  src/nbla/function/generic/batch_normalization.cpp
  src/nbla/imperative.cpp
Labels: release-note-op-layer

#554 WarpByFlow function
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/warp_by_flow.hpp
  python/test/function/test_warp_by_flow.py
  src/nbla/function/generic/warp_by_flow.cpp
Labels: release-note-op-layer

#553 Implement batch_det
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/batch_det.hpp
  python/test/function/test_batch_det.py
  src/nbla/function/generic/batch_det.cpp
Labels: release-note-op-layer

#417 Suppress unused variable warnings at global_average_pooling.cpp
  src/nbla/function/generic/global_average_pooling.cpp
Labels: release-note-ignore

#555 Add opset 10,11 support for ONNX Exporter.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#557 Fix nnabla.proto save problem
  python/src/nnabla/utils/save.py
Labels: release-note-bugfix

#558 Update API LEVEL
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
Labels: release-note-format-converter

#559 Remove binary-only option from pip in Dockerfile.
  docker/development/Dockerfile.android
  docker/development/Dockerfile.android-test
  docker/development/Dockerfile.auto-format
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-armhf
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.document
  docker/development/Dockerfile.onnx-test
  docker/development/Dockerfile.onnx-test-armhf
  docker/development/Dockerfile.onnx-test-ppc64le
  docker/development/Dockerfile.tf-test
Labels: release-note-build

#556 Improve ONNX Exporter for SNPE.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#560 Fix coding error.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-bugfix

#561 Add opset 10,11 support for ONNX Importer.
  python/src/nnabla/utils/converter/onnx/importer.py
  python/src/nnabla/utils/converter/onnx/utils.py
Labels: release-note-format-converter
