Repository sony/nnabla, pull requests merged in 2019-04, with the labels that each got.

#380 Spectral Normalization
  doc/python/api/parametric_function.rst
  python/src/nnabla/parametric_functions.py
  python/test/test_parametric_functions.py
Labels: enhancement

#377 [models] Add NIN
  doc/python/api/models/imagenet.rst
  python/src/nnabla/models/imagenet/__init__.py
  python/src/nnabla/models/imagenet/nin.py
  python/test/models/test_imagenet.py
Labels: release-note-nnabla-models

#389 [Models] VGG
  doc/python/api/models/imagenet.rst
  python/src/nnabla/models/imagenet/__init__.py
  python/src/nnabla/models/imagenet/vgg.py
  python/test/models/test_imagenet.py
Labels: release-note-nnabla-models

#393 Expose data pointer to python layer to some cases (e.g., for DALI)
  include/nbla/nd_array.hpp
  include/nbla/synced_array.hpp
  python/src/nnabla/_nd_array.pxd
  python/src/nnabla/_nd_array.pyx
  src/nbla/nd_array.cpp
  src/nbla/synced_array.cpp
Labels: enhancement

#394 Support backward of BatchNormalization for batch_stat=False
  include/nbla/function/batch_normalization.hpp
  python/test/function/test_batch_normalization.py
  src/nbla/function/generic/batch_normalization.cpp
Labels: release-note-op-layer

#390 correct layers and modify checking method
  doc/python/api/models/imagenet.rst
  python/src/nnabla/utils/nnp_graph.py
Labels: release-note-doc

#395 Add random_choice function and tests.
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/random_choice.hpp
  python/test/function/test_random_choice.py
  src/nbla/function/generic/random_choice.cpp
Labels: enhancement

#391 Add TopKDataCuda and TopKGradCuda function implementations.
  python/test/function/test_top_k_data.py
  python/test/function/test_top_k_grad.py
Labels: enhancement

#396 Add tile function (c.f. numpy.tile or torch.repeat)
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/tile.hpp
  include/nbla/utils/nd_index.hpp
  python/src/nnabla/functions.py
  python/test/function/test_tile.py
  src/nbla/function/generic/tile.cpp
Labels: enhancement

#397 Add AdaBound & AMSBound
  build-tools/code_generator/solver_types.yaml
  build-tools/code_generator/solvers.yaml
  doc/python/api/solver.rst
  include/nbla/solver/adabound.hpp
  include/nbla/solver/amsbound.hpp
  python/test/solver/test_adabound.py
  python/test/solver/test_amsbound.py
  src/nbla/solver/generic/adabound.cpp
  src/nbla/solver/generic/amsbound.cpp
Labels: release-note-utility

#400 Add RNN/LSTM/GRU to parametric function test
  python/test/test_parametric_functions.py
Labels: release-note-ignore

#398 fix docstrings for `data_iterator` and `data_source`
  python/src/nnabla/utils/data_iterator.py
Labels: release-note-ignore

#412 Add InceptionV3 model
  doc/python/api/models/imagenet.rst
  python/src/nnabla/models/imagenet/__init__.py
  python/src/nnabla/models/imagenet/inception.py
  python/test/models/test_imagenet.py
Labels: release-note-nnabla-models

#244 Implement assign function
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/assign.hpp
  python/test/function/test_assign.py
  src/nbla/function/generic/assign.cpp
Labels: release-note-op-layer

#403 Add variable name option to dump command.
  doc/python/command_line_interface.rst
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/converter/commands.py
Labels: enhancement

#415 bugfix mnist data reading
  examples/cpp/mnist_collection/mnist_data.hpp
  examples/cpp/mnist_training/mnist_training.hpp
Labels: bug, release-note-bugfix
