Repository sony/nnabla, pull requests merged in 2019-05, with the labels that each got.

#419 Add tests for min and max function when returning indices.
  python/test/function/test_reduction.py
Labels: bug

#422 gather_nd and selection by index variable (advanced indexing)
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/gather_nd.hpp
  python/src/nnabla/_indexing.pyx
  python/src/nnabla/functions.py
  python/test/function/test_gather.py
  python/test/function/test_slice.py
  python/test/test_ndarray_indexing.py
  src/nbla/function/generic/gather_nd.cpp
  src/nbla/function/generic/slice.cpp
Labels: enhancement

#440 FIX: Add a missing implemenation to nnp::Monitor
  src/nbla_utils/nnp.cpp
Labels: bug

#441 Add versions v1.0 and v1.1 to SqueezeNet model
  doc/python/api/models/imagenet.rst
  python/src/nnabla/models/imagenet/squeezenet.py
  python/test/models/test_imagenet.py
Labels: release-note-nnabla-models

#446 fix valgrind warning
  src/nbla_utils/nnp_impl.cpp
Labels: bug

#448 Add more operator support for onnx import, and update doc.
  doc/python/file_format_converter/onnx/operator_coverage.rst
  python/src/nnabla/utils/converter/onnx/importer.py
  python/test/utils/conversion/importer_funcs_opset.yaml
Labels: enhancement

#447 Improve creating cache from CSV dataset
  build-tools/make/build.mk
  python/src/nnabla/utils/cli/conv_dataset.py
  python/src/nnabla/utils/create_cache.py
  python/src/nnabla/utils/load.py
  python/test/function/test_random_crop.py
Labels: enhancement

#449 nnpgraph refactoring
  python/src/nnabla/utils/nnp_graph.py
Labels: release-note-ignore

#450 [python] Changes definition of Variable comparison and hash
  doc/conf.py
  python/src/nnabla/_variable.pyx
  python/src/nnabla/parameter.py
  python/test/test_parameter.py
  python/test/test_variable.py
Labels: release-note-core
