Repository sony/nnabla, pull requests merged in 2019-10, with the labels that each got.

#522 Added missing imports in imagenet model doc
  doc/python/api/models/imagenet.rst
Labels: release-note-doc

#523 Fix min-max-quantize
  python/src/nnabla/parametric_functions.py
  python/test/test_parametric_functions.py
Labels: bug

#524 MultiHead Attention
  doc/python/api/function.rst
  doc/python/api/parametric_function.rst
  python/src/nnabla/functions.py
  python/src/nnabla/parametric_functions.py
  python/test/test_parametric_functions.py
Labels: release-note-op-layer

#525 Exit with 0 when no tests in pytest
  build-tools/make/build.mk
  build-tools/make/pytest.sh
Labels: release-note-build

#526 Added autoforward for pycpp
  examples/cpp/mnist_collection/dcgan_training.hpp
  examples/cpp/mnist_collection/lenet_training.hpp
  examples/cpp/mnist_collection/resnet_training.hpp
  examples/cpp/mnist_collection/siamese_training.hpp
  examples/cpp/mnist_collection/train_dcgan.cpp
  examples/cpp/mnist_collection/train_lenet_classifier.cpp
  examples/cpp/mnist_collection/train_resnet_classifier.cpp
  examples/cpp/mnist_collection/train_siamese.cpp
  examples/cpp/mnist_collection/train_vae.cpp
  examples/cpp/mnist_collection/train_vat.cpp
  examples/cpp/mnist_collection/vae_training.hpp
  examples/cpp/mnist_collection/vat_training.hpp
  include/nbla/auto_forward.hpp
  src/nbla/auto_forward.cpp
  src/nbla/functions.cpp.tmpl
  src/nbla/parametric_functions.cpp
Labels: enhancement

#527 Use dtype of RHS in NdArray.data setter
  python/src/nnabla/_nd_array.pyx
  python/src/nnabla/_variable.pyx
  python/src/nnabla/function.pyx.tmpl
  python/src/nnabla/logger.py
  python/src/nnabla/parametric_functions.py
  python/test/communicator/test_all_reduce.py
  python/test/function/test_clip_by_value.py
  python/test/function/test_max_pooling.py
  python/test/function/test_random_choice.py
  python/test/nbla_test_utils.py
  python/test/test_nd_array.py
  python/test/test_save_load_parameters.py
Labels: release-note-core

#530 Fix layer_normalization parameter shape & improve performance of normalization functions
  python/src/nnabla/normalization_functions.py
  python/src/nnabla/parametric_functions.py
  python/test/communicator/test_sync_batch_normalization.py
  python/test/function/test_batch_normalization.py
  python/test/function/test_fused_batch_normalization.py
  python/test/function/test_group_normalization.py
  python/test/function/test_instance_normalization.py
  python/test/function/test_layer_normalization.py
  python/test/function/test_weight_standardization.py
  python/test/test_parametric_functions.py
Labels: release-note-bugfix

#531 fix solver.load_states()
  python/src/nnabla/solver.pyx.tmpl
Labels: release-note-bugfix

#532 Fix bug in graph engine for shared variable
  python/src/nnabla/grad.py
  python/test/test_grad.py
  python/test/test_graph.py
  src/nbla/computation_graph/variable.cpp
Labels: bug, release-note-bugfix

#534 Fix converter nnb-template error
  python/src/nnabla/utils/cli/convert.py
Labels: release-note-format-converter

#535 Remove non-used nnb params and enable SIGN
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/converter/nnablart/nnb.py
  python/src/nnabla/utils/converter/nnablart/utils.py
Labels: release-note-format-converter

#537 Tensorflow network Optimization for converter from onnx
  doc/python/command_line_interface.rst
  python/src/nnabla/utils/cli/cli.py
  python/src/nnabla/utils/cli/optimize_pb_model.py
  python/src/nnabla/utils/converter/tensorflow/parsetab.py
  python/src/nnabla/utils/converter/tensorflow/refine_graph.py
  python/src/nnabla/utils/converter/tensorflow/refine_parser.py
Labels: release-note-format-converter
