Repository sony/nnabla, pull requests merged in 2019-11, with the labels that each got.

#538 Trasnformer Encoder/Decoder
  doc/python/api/parametric_function.rst
  python/src/nnabla/functions.py
  python/src/nnabla/parametric_functions.py
  python/test/test_parametric_functions.py
Labels: release-note-op-layer

#540 Add NNabla func support for onnx exporter:
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#541 Add ONNX op support for onnx importer:
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-format-converter

#542 Fix coding error.
  python/src/nnabla/utils/converter/tensorflow/refine_parser.py
Labels: release-note-format-converter

#543 Add quantization document
  doc/python/file_format_converter/compress_network.rst
  doc/python/file_format_converter/compress_network_files/buffer_size.png
  doc/python/file_format_converter/compress_network_files/f_bw_bc.png
  doc/python/file_format_converter/compress_network_files/f_bw_bc.xcf
  doc/python/file_format_converter/compress_network_files/float_binary_training.png
  doc/python/file_format_converter/compress_network_files/float_binary_training.xcf
  doc/python/file_format_converter/compress_network_files/float_training.png
  doc/python/file_format_converter/compress_network_files/float_training_clr.png
  doc/python/file_format_converter/compress_network_files/float_training_clr.xcf
  doc/python/file_format_converter/compress_network_files/fp_big.png
  doc/python/file_format_converter/compress_network_files/fp_compare.png
  doc/python/file_format_converter/compress_network_files/fp_small.png
  doc/python/file_format_converter/compress_network_files/func_exec.png
  doc/python/file_format_converter/compress_network_files/histogram_add2cudacudnn_1.png
  doc/python/file_format_converter/compress_network_files/histogram_add2cudacudnn_2.png
  doc/python/file_format_converter/compress_network_files/histogram_add2cudacudnn_2.xcf
  doc/python/file_format_converter/file_format_converter.rst
Labels: release-note-doc

#539 Fix and improve debug assertions in ndi helper functions.
  include/nbla/utils/nd_index.hpp
Labels: release-note-bugfix

#547 Orthogonal Initializer
  doc/python/api/parametric_function.rst
  python/src/nnabla/initializer.py
  python/test/test_initializer.py
Labels: release-note-utility

#549 Added guidelines for auto format
  CONTRIBUTING.md
Labels: release-note-doc

#548 Allow clip_by_value to get scalar values as threshold
  python/src/nnabla/functions.py
  python/test/function/test_clip_by_value.py
Labels: release-note-ignore
