Repository sony/nnabla, pull requests merged in 2019-07, with the labels that each got.

#481 [Fix] Force parameter shape as ints for backward compatibility
  python/src/nnabla/parameter.py
Labels: release-note-bugfix

#480 [Models] auto-forward support and modified parameter loading method.
  python/src/nnabla/utils/nnp_graph.py
Labels: release-note-nnabla-models

#483 LARS (Layer-wise Adaptive Rate Scaling)
  build-tools/code_generator/solver_types.yaml
  build-tools/code_generator/solvers.yaml
  doc/python/api/solver.rst
  include/nbla/solver/lars.hpp
  python/test/solver/test_lars.py
  src/nbla/solver/generic/lars.cpp
Labels: enhancement

#485 Fix test on ppc64le
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-armhf
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.onnx-test
  docker/development/Dockerfile.onnx-test-armhf
  docker/development/Dockerfile.onnx-test-ppc64le
  python/requirements.txt
  python/setup.py
  python/test/test_graph.py
Labels: release-note-build

#484 [Tutorial] Add Finetuning Tutorial Using Pre-trained Models
  doc/python/tutorial/model_finetuning.rst
  doc/python/tutorial/model_finetuning_files/model_finetuning_11_0.png
  doc/python/tutorial/model_finetuning_files/model_finetuning_29_1.png
  doc/python/tutorial/model_finetuning_files/model_finetuning_36_0.png
  tutorial/caltech101_data.py
  tutorial/finetuning.py
  tutorial/model_finetuning.ipynb
Labels: release-note-doc

#482 fix normalization adaptive parameters
  python/src/nnabla/parametric_functions.py
  python/test/test_parametric_functions.py
Labels: release-note-break-compat

#489 [Models] Add ShuffleNet
  doc/python/api/models/imagenet.rst
  python/src/nnabla/models/imagenet/__init__.py
  python/src/nnabla/models/imagenet/shufflenet.py
  python/test/models/test_imagenet.py
Labels: release-note-nnabla-models

#491 Enable DataSource Shuffling During Training
  python/src/nnabla/utils/data_source_implements.py
Labels: release-note-core

#493 Use module-wise random generator to initialize parameter weights
  python/src/nnabla/initializer.py
  python/src/nnabla/random.py
  python/test/test_forward_all.py
  python/test/test_graph.py
  python/test/test_initializer.py
Labels: bug, enhancement

#494 Add setitem methods for NdArray and Variable
  python/src/nnabla/_indexing.pxd
  python/src/nnabla/_indexing.pyx
  python/src/nnabla/_nd_array.pyx
  python/src/nnabla/_variable.pyx
  python/test/test_indexing.py
  python/test/test_ndarray_indexing.py
Labels: enhancement
