Repository sony/nnabla, pull requests merged in 2019-06, with the labels that each got.

#452 Fix example doc in YOLOv2 model
  doc/python/api/models/object_detection.rst
Labels: release-note-ignore

#465 [Models] Add GoogLeNet Model
  doc/python/api/models/imagenet.rst
  python/src/nnabla/models/imagenet/__init__.py
  python/src/nnabla/models/imagenet/googlenet.py
  python/test/models/test_imagenet.py
Labels: release-note-nnabla-models

#460 Add missing brackets in documentation example code
  python/src/nnabla/functions.py
Labels: bug

#459 Add support for rectangular window
  python/src/nnabla/functions.py
  python/test/function/test_stft.py
Labels: enhancement

#456 [c++] Fix accumulation logic in grpah engine for better efficiency
  include/nbla/synced_array.hpp
  src/nbla/computation_graph/variable.cpp
  src/nbla/synced_array.cpp
Labels: release-note-core

#475 Allow no --label option in nnabla_cli plot_series
  python/src/nnabla/utils/cli/plot.py
Labels: bug

#474 Change default initial weight value of PReLU
  python/src/nnabla/_variable.pyx
  python/src/nnabla/parametric_functions.py
  python/test/test_parametric_functions.py
Labels: release-note-break-compat

#476 Add scatter_nd function and tests.
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/scatter_nd.hpp
  python/src/nnabla/functions.py
  python/test/function/test_scatter_nd.py
  src/nbla/function/generic/scatter_nd.cpp
Labels: enhancement
