Repository sony/nnabla, pull requests merged in 2019-09, with the labels that each got.

#513 Add DeepLabV3+ model as a pretrained model API
  doc/python/api/models.rst
  doc/python/api/models/semantic_segmentation.rst
  python/setup.py
  python/src/nnabla/models/semantic_segmentation/__init__.py
  python/src/nnabla/models/semantic_segmentation/base.py
  python/src/nnabla/models/semantic_segmentation/deeplabv3plus.py
  python/src/nnabla/models/semantic_segmentation/image_preprocess.py
  python/src/nnabla/models/semantic_segmentation/utils.py
  python/src/nnabla/models/semantic_segmentation/voc.names
  python/test/models/test_deeplabv3plus.py
Labels: release-note-nnabla-models

#512 Fix build
  CMakeLists.txt
  python/setup.py
Labels: release-note-build

#519 Min-max quantization
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  doc/python/api/parametric_function.rst
  include/nbla/function/min_max_quantize.hpp
  python/src/nnabla/backward_function/min_max_quantize.py
  python/src/nnabla/functions.py
  python/src/nnabla/parametric_functions.py
  python/test/function/test_min_max_quantize.py
  python/test/test_parametric_functions.py
  src/nbla/function/generic/min_max_quantize.cpp
Labels: enhancement
