Repository sony/nnabla, pull requests merged in 2020-11, with the labels that each got.

#733 Fix the docs related to the output maps
  build-tools/code_generator/functions.yaml
Labels: release-note-bugfix

#734 Build with chocolatey environment.
  build-tools/make/options.mk
  build-tools/msvc/build_cpplib.bat
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/clean.bat
  build-tools/msvc/test.bat
  build-tools/msvc/test_nbla.bat
  build-tools/msvc/tools/build_libarchive.bat
  build-tools/msvc/tools/build_protobuf.bat
  build-tools/msvc/tools/build_zlib.bat
  build-tools/msvc/tools/default_folders.bat
  build-tools/msvc/tools/default_settings.bat
  build-tools/msvc/tools/env.bat
  build-tools/msvc/tools/python_env.bat
  build-tools/msvc/tools/python_env_cleanup.bat
  doc/build/build_cpp_utils_windows.md
  doc/build/build_windows.md
  docker/development/Dockerfile.build
  src/nbla_utils/test/test_load_save.cpp
  third_party/CMakeLists.txt
Labels: release-note-build

#732 Inplace for unary/binary arithmetic functions
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  examples/cpp/mnist_collection/siamese_training.hpp
  examples/cpp/mnist_collection/vat_training.hpp
  include/nbla/function/add_scalar.hpp
  include/nbla/function/bc_add2.hpp
  include/nbla/function/div2.hpp
  include/nbla/function/mul2.hpp
  include/nbla/function/mul_scalar.hpp
  include/nbla/function/pow2.hpp
  include/nbla/function/pow_scalar.hpp
  include/nbla/function/sub2.hpp
  include/nbla/function/utils/base_transform_binary.hpp
  include/nbla/function/utils/base_transform_unary.hpp
  python/src/nnabla/_nd_array.pyx
  python/src/nnabla/_variable.pyx
  python/test/function/test_add_scalar.py
  python/test/function/test_mul_scalar.py
  python/test/function/test_pow_scalar.py
  python/test/function/test_transform_binary.py
  python/test/test_variable_arithmetic_ops.py
  src/nbla/function/generic/add2.cpp
  src/nbla/function/generic/add_scalar.cpp
  src/nbla/function/generic/batch_det.cpp
  src/nbla/function/generic/batch_inv.cpp
  src/nbla/function/generic/batch_normalization.cpp
  src/nbla/function/generic/bc_add2.cpp
  src/nbla/function/generic/binary_weight_affine.cpp
  src/nbla/function/generic/binary_weight_convolution.cpp
  src/nbla/function/generic/clip_grad_by_norm.cpp
  src/nbla/function/generic/dequantize_linear.cpp
  src/nbla/function/generic/div2.cpp
  src/nbla/function/generic/gru.cpp
  src/nbla/function/generic/lstm.cpp
  src/nbla/function/generic/min_max_quantize.cpp
  src/nbla/function/generic/mul2.cpp
  src/nbla/function/generic/mul_scalar.cpp
  src/nbla/function/generic/pow2.cpp
  src/nbla/function/generic/pow_scalar.cpp
  src/nbla/function/generic/quantize_linear.cpp
  src/nbla/function/generic/sub2.cpp
  src/nbla/function/generic/weight_normalization.cpp
  src/nbla/functions.cpp.tmpl
Labels: release-note-op-layer

#736 Use the new h5py v3 data access method.
  python/src/nnabla/utils/data_source.py
  python/src/nnabla/utils/data_source_implements.py
Labels: release-note-bugfix

#735 Add missing format character in function parameter check.
  src/nbla/function/generic/depthwise_convolution.cpp
  src/nbla/function/generic/depthwise_deconvolution.cpp
Labels: release-note-bugfix

#738 Limit onnx version to 1.6.0
  python/setup.py
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-build

#739 Fix issue that BatchMatmul adds new features to cause the converter t…
  python/src/nnabla/utils/converter/onnx/exporter.py
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-bugfix

#740 fix error when no .protobuf file and parameter [] operator.
  src/nbla/parametric_functions.cpp
  src/nbla_utils/parameters.cpp
Labels: release-note-format-converter

#742 Add ScatterAdd Function
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/scatter_add.hpp
  python/src/nnabla/backward_function/scatter_add.py
  python/src/nnabla/functions.py
  python/test/function/test_scatter_add.py
  src/nbla/function/generic/scatter_add.cpp
Labels: release-note-op-layer

#743 Add Adabelief solver proposed by Juntang Zhuang
  build-tools/code_generator/solver_types.yaml
  build-tools/code_generator/solvers.yaml
  doc/python/api/solver.rst
  include/nbla/solver/adabelief.hpp
  python/src/nnabla/utils/load.py
  python/src/nnabla/utils/save.py
  python/test/solver/test_adabelief.py
  src/nbla/solver/generic/adabelief.cpp
  src/nbla_utils/nnp_impl_create_solver.cpp
Labels: release-note-op-layer

#744 Norm and NormNormalization
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/norm.hpp
  include/nbla/function/norm_normalization.hpp
  python/src/nnabla/backward_function/norm.py
  python/src/nnabla/backward_function/norm_normalization.py
  python/src/nnabla/functions.py
  python/test/function/test_norm.py
  python/test/function/test_norm_normalization.py
  src/nbla/function/generic/norm.cpp
  src/nbla/function/generic/norm_normalization.cpp
Labels: release-note-op-layer

#745 Improve building dockerfiles
  build-tools/make/build-with-docker.mk
  docker/py35/Dockerfile
  docker/py36/Dockerfile
  docker/py37/Dockerfile
  docker/py38/Dockerfile
  docker/runtime/Dockerfile
  python/requirements.txt
  python/setup.py
Labels: release-note-build

#746 fix document error for to_dlpack
  python/src/nnabla/utils/dlpack.pyx
Labels: release-note-doc

#747 Feature/20200921 separate tf converter from nnabla
  CMakeLists.txt
  build-tools/make/build.mk
  build-tools/msvc/test.bat
  doc/python/file_format_converter/file_format_converter.rst
  docker/development/Dockerfile.tf-test
  python/setup.py
  python/src/nnabla/utils/converter/commands.py
  python/src/nnabla/utils/converter/onnx/importer.py
  python/src/nnabla/utils/converter/setup.py
  python/src/nnabla/utils/converter/tensorflow/exporter.py
  python/src/nnabla/utils/converter/tensorflow/importer.py
  third_party/patches/onnx-tensorflow/0001-Fix-Reshape-and-SELU.patch
  third_party/patches/tensorflow-onnx/0001-Fix-NotEqual-Equal-and-ConvTranspose.patch
Labels: release-note-format-converter

#750 Fix norm api level and function id
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
Labels: release-note-bugfix

#751 Enabla GRU for c-runtime.
  python/src/nnabla/utils/converter/nnablart/nnb.py
  python/src/nnabla/utils/converter/nnablart/resolver.py
Labels: release-note-format-converter

#752 Change libarchive location
  CMakeLists.txt
  build-tools/msvc/tools/build_libarchive.bat
  docker/development/Dockerfile.build
  docker/development/Dockerfile.onnx-test
  docker/development/Dockerfile.tf-test
  python/src/nnabla/utils/converter/setup.py
Labels: release-note-build

#753 update dockerfile to install nnabla_tf_converter
  build-tools/make/build-with-docker.mk
  docker/py36/Dockerfile
  docker/py37/Dockerfile
  docker/runtime/Dockerfile
Labels: release-note-format-converter
