Repository sony/nnabla, pull requests merged in 2020-07, with the labels that each got.

#677 Fix Documentation Errors
  build-tools/code_generator/solvers.yaml
  doc/python/command_line_interface.rst
  python/src/nnabla/utils/nnp_graph.py
Labels: release-note-doc

#680 change naming rule for repeat node
  python/src/nnabla/utils/converter/nnabla/expander.py
  python/src/nnabla/utils/converter/nnabla/exporter.py
  src/nbla_utils/nnp_network_expander.cpp
Labels: release-note-format-converter

#681 Fix Deconvolution for ONNX Exporter.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#683 add infer API and param data type option
  python/src/nnabla/utils/cli/forward.py
  python/src/nnabla/utils/data_source_loader.py
  src/nbla_cli/nbla_infer.cpp
Labels: release-note-utility

#684 Double Backward Enhancement
  doc/python/api/function.rst
  python/src/nnabla/backward_function/acos.py
  python/src/nnabla/backward_function/acosh.py
  python/src/nnabla/backward_function/asin.py
  python/src/nnabla/backward_function/asinh.py
  python/src/nnabla/backward_function/atan.py
  python/src/nnabla/backward_function/atanh.py
  python/src/nnabla/backward_function/backward_function.py
  python/src/nnabla/backward_function/cos.py
  python/src/nnabla/backward_function/cosh.py
  python/src/nnabla/backward_function/sin.py
  python/src/nnabla/backward_function/sinh.py
  python/src/nnabla/backward_function/tan.py
  python/src/nnabla/function.pxd.tmpl
  python/src/nnabla/function.pyx.tmpl
  python/src/nnabla/grad.py
  python/test/function/test_acos.py
  python/test/function/test_acosh.py
  python/test/function/test_asin.py
  python/test/function/test_asinh.py
  python/test/function/test_atan.py
  python/test/function/test_atanh.py
  python/test/function/test_cos.py
  python/test/function/test_cosh.py
  python/test/function/test_sin.py
  python/test/function/test_sinh.py
  python/test/function/test_tan.py
  python/test/test_graph.py
  python/test/test_python_function.py
Labels: release-note-op-layer

#682 Fix conflicts between nodes with same output name.
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-format-converter

#685 nnp refactor, enable module-style network definition
  doc/python/api/graph_def.rst
  doc/python/api/module.rst
  doc/python/tutorial/save_load_model.rst
  python/setup.py
  python/src/nnabla/__init__.py
  python/src/nnabla/core/__init__.py
  python/src/nnabla/core/graph_def.py
  python/src/nnabla/core/module.py
  python/src/nnabla/core/modules.py
  python/src/nnabla/experimental/tb_graph_writer.py
  python/src/nnabla/function.pyx.tmpl
  python/test/core/conftest.py
  python/test/core/test_module.py
Labels: release-note-utility

#686 Add licenses and Notice
  CMakeLists.txt
  NOTICE.md
  README.md
  build-tools/make/options.mk
  docker/development/Dockerfile.build
  python/setup.py
  src/nbla/CMakeLists.txt
  third_party/CMakeLists.txt
  third_party/LICENSES.md
Labels: release-note-doc

#687 Add DLPack interface to share a tensor on host or device among frameworks and libraries without copy
  .gitignore
  CMakeLists.txt
  build-tools/make/build.mk
  doc/python/api/nd_array.rst
  doc/python/api/utils.rst
  doc/python/api/utils/dlpack.rst
  include/nbla/array.hpp
  include/nbla/array/cpu_dlpack_array.hpp
  include/nbla/array/dlpack_array.hpp
  include/nbla/array_registry.hpp
  include/nbla/memory/allocator.hpp
  include/nbla/synced_array.hpp
  include/nbla/utils/dlpack_array_registry.hpp
  include/nbla/utils/dlpack_utils.hpp
  include/third_party/dlpack/dlpack.h
  python/setup.py
  python/src/nnabla/_nd_array.pyx
  python/src/nnabla/_variable.pyx
  python/src/nnabla/experimental/mixed_precision_training.py
  python/src/nnabla/experimental/trainers/updater.py
  python/src/nnabla/function.pyx.tmpl
  python/src/nnabla/grad.py
  python/src/nnabla/utils/dlpack.pxd
  python/src/nnabla/utils/dlpack.pyx
  python/test/utils/test_dlpack.py
  src/nbla/array/cpu_array-internal.hpp
  src/nbla/array/cpu_array.cpp
  src/nbla/array/cpu_dlpack_array.cpp
  src/nbla/array/dlpack_array.cpp
  src/nbla/array_registry.cpp
  src/nbla/function/generic/dequantize_linear.cpp
  src/nbla/function/generic/quantize_linear.cpp
  src/nbla/init.cpp.tmpl
  src/nbla/memory/allocator.cpp
  src/nbla/synced_array.cpp
  src/nbla/utils/dlpack_array_registry.cpp
  src/nbla/utils/dlpack_utils.cpp
  third_party/CMakeLists.txt
  third_party/LICENSES.md
Labels: release-note-utility

#688 SpatialTransformer
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/affine_grid.hpp
  include/nbla/function/warp_by_grid.hpp
  include/nbla/imperative.hpp
  python/src/nnabla/backward_function/affine_grid.py
  python/src/nnabla/backward_function/warp_by_grid.py
  python/test/function/refs.py
  python/test/function/test_affine_grid.py
  python/test/function/test_warp_by_grid.py
  src/nbla/function/generic/affine_grid.cpp
  src/nbla/function/generic/warp_by_grid.cpp
  src/nbla/imperative.cpp
Labels: release-note-op-layer

#689 Make scatter_nd work in static graph mode.
  build-tools/code_generator/functions.yaml
  include/nbla/function/scatter_nd.hpp
  python/src/nnabla/_indexing.pyx
  python/src/nnabla/_variable.pyx
  python/src/nnabla/functions.py
  python/test/test_indexing.py
  src/nbla/function/generic/scatter_nd.cpp
Labels: release-note-bugfix

#691 Fix a specific pattern of fused convolution
  python/test/function/test_fused_convolution.py
  src/nbla/function/generic/fused_convolution.cpp
Labels: release-note-ignore

#690 Fix Gelu Backward
  include/nbla/function/gelu.hpp
  python/test/function/test_gelu.py
Labels: bug, release-note-bugfix

#693 Disable gradient inplace and its check
  include/nbla/computation_graph/function.hpp
  include/nbla/function.hpp
  include/nbla/function/add2.hpp
  include/nbla/function/function_impl.hpp.tmpl
  include/nbla/function/leaky_relu.hpp
  include/nbla/function/random_erase.hpp
  include/nbla/function/relu.hpp
  include/nbla/function/reshape.hpp
  python/src/nnabla/function.pxd.tmpl
  python/src/nnabla/function.pyx.tmpl
  python/src/nnabla/utils/cli/profile.py
  python/src/nnabla/utils/network.py
  python/test/function/test_interpolate.py
  python/test/nbla_test_utils.py
  python/test/test_variable.py
  src/nbla/computation_graph/function.cpp
  src/nbla/computation_graph/variable.cpp
  src/nbla/function.cpp
  src/nbla/function/generic/add2.cpp
  src/nbla/function/generic/fused_batch_normalization.cpp
  src/nbla/function/generic/leaky_relu.cpp
  src/nbla/function/generic/random_erase.cpp
  src/nbla/function/generic/relu.cpp
  src/nbla/function/generic/reshape.cpp
Labels: release-note-op-layer

#694 cpu gpu load measure config separately
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/progress.py
Labels: release-note-utility

#695 Specify the converter related packages version in the doc.
  .gitignore
  doc/python/command_line_interface.rst
  doc/python/file_format_converter/file_format_converter.rst
  docker/development/Dockerfile.tf-test
  python/requirements.txt
  python/src/nnabla/utils/converter/onnx/exporter.py
  third_party/patches/onnx-tensorflow/0001-Fix-Reshape-and-SELU.patch
  third_party/patches/tensorflow-onnx/0001-Fix-NotEqual-Equal-and-ConvTranspose.patch
Labels: release-note-doc
