Repository sony/nnabla, pull requests merged in 2020-04, with the labels that each got.

#611 Double Backward for ChannelLast and Half Type
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  doc/contributing/add_function.md
  include/nbla/function/interpolate.hpp
  include/nbla/function/max_pooling_backward.hpp
  python/src/nnabla/backward_function/average_pooling.py
  python/src/nnabla/backward_function/convolution.py
  python/src/nnabla/backward_function/deconvolution.py
  python/src/nnabla/backward_function/interpolate.py
  python/src/nnabla/backward_function/max_pooling.py
  python/src/nnabla/backward_function/sum_pooling.py
  python/src/nnabla/functions.py
  python/src/nnabla/grad.py
  python/test/function/test_abs.py
  python/test/function/test_add2.py
  python/test/function/test_add_scalar.py
  python/test/function/test_affine.py
  python/test/function/test_average_pooling.py
  python/test/function/test_broadcast.py
  python/test/function/test_concatenate.py
  python/test/function/test_convolution.py
  python/test/function/test_deconvolution.py
  python/test/function/test_div2.py
  python/test/function/test_elu.py
  python/test/function/test_exp.py
  python/test/function/test_hard_sigmoid.py
  python/test/function/test_hard_tanh.py
  python/test/function/test_identity.py
  python/test/function/test_interpolate.py
  python/test/function/test_leaky_relu.py
  python/test/function/test_log.py
  python/test/function/test_log_sigmoid.py
  python/test/function/test_max_pooling.py
  python/test/function/test_maximum2.py
  python/test/function/test_maximum_scalar.py
  python/test/function/test_minimum2.py
  python/test/function/test_minimum_scalar.py
  python/test/function/test_mul2.py
  python/test/function/test_mul_scalar.py
  python/test/function/test_pow2.py
  python/test/function/test_pow_scalar.py
  python/test/function/test_prune.py
  python/test/function/test_r_div_scalar.py
  python/test/function/test_r_sub_scalar.py
  python/test/function/test_reduction.py
  python/test/function/test_relu.py
  python/test/function/test_relu6.py
  python/test/function/test_reshape.py
  python/test/function/test_selu.py
  python/test/function/test_sigmoid.py
  python/test/function/test_split.py
  python/test/function/test_stack.py
  python/test/function/test_sub2.py
  python/test/function/test_sum_pooling.py
  python/test/function/test_swish.py
  python/test/function/test_tanh.py
  python/test/nbla_test_utils.py
  src/nbla/function/generic/interpolate.cpp
  src/nbla/function/generic/max_pooling_backward.cpp
Labels: release-note-op-layer

#614 Fix file like object save load
  python/src/nnabla/parameter.py
  python/src/nnabla/utils/get_file_handle.py
  python/src/nnabla/utils/load.py
  python/src/nnabla/utils/save.py
  python/test/utils/test_save_load.py
Labels: release-note-utility

#615 feat: support loading audio files through csv file
  python/src/nnabla/utils/audio_utils/backend_manager.py
  python/src/nnabla/utils/audio_utils/common.py
  python/src/nnabla/utils/audio_utils/pydub_utils.py
  python/src/nnabla/utils/data_source_loader.py
Labels: release-note-utility

#618 Unpooling with Channel Last
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/unpooling.hpp
  python/src/nnabla/backward_function/unpooling.py
  python/src/nnabla/grad.py
  python/test/function/test_unpooling.py
  src/nbla/function/generic/unpooling.cpp
Labels: release-note-op-layer

#612 Remove unused imports, Fix spelling mistakes, Simplify if conditions and chained comparisons.
  python/src/nnabla/backward_function/batch_normalization.py
  python/src/nnabla/backward_function/warp_by_flow.py
  python/src/nnabla/experimental/graph_converters/batch_normalization_folded.py
  python/src/nnabla/experimental/graph_converters/batch_normalization_linear.py
  python/src/nnabla/experimental/parametric_function_class/deconvolution.py
  python/src/nnabla/ext_utils.py
  python/src/nnabla/functions.py
  python/src/nnabla/grad.py
  python/src/nnabla/logger.py
  python/src/nnabla/models/imagenet/alexnet.py
  python/src/nnabla/models/imagenet/base.py
  python/src/nnabla/models/imagenet/densenet.py
  python/src/nnabla/models/imagenet/googlenet.py
  python/src/nnabla/models/imagenet/inception.py
  python/src/nnabla/models/imagenet/mobilenet.py
  python/src/nnabla/models/imagenet/nin.py
  python/src/nnabla/models/imagenet/resnet.py
  python/src/nnabla/models/imagenet/resnext.py
  python/src/nnabla/models/imagenet/senet.py
  python/src/nnabla/models/imagenet/shufflenet.py
  python/src/nnabla/models/imagenet/squeezenet.py
  python/src/nnabla/models/imagenet/vgg.py
  python/src/nnabla/models/imagenet/xception.py
  python/src/nnabla/models/object_detection/base.py
  python/src/nnabla/models/object_detection/utils.py
  python/src/nnabla/models/object_detection/yolov2.py
  python/src/nnabla/models/semantic_segmentation/base.py
  python/src/nnabla/models/semantic_segmentation/deeplabv3plus.py
  python/src/nnabla/models/semantic_segmentation/image_preprocess.py
  python/src/nnabla/models/utils.py
  python/src/nnabla/monitor.py
  python/src/nnabla/parameter.py
  python/src/nnabla/parametric_functions.py
  python/src/nnabla/testing/__init__.py
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/converter/commands.py
  python/src/nnabla/utils/converter/nnablart/nnb.py
  python/src/nnabla/utils/data_source.py
  python/test/function/test_hard_sigmoid.py
  python/test/function/test_hard_tanh.py
  python/test/function/test_stack.py
  python/test/function/test_where.py
  python/test/nbla_test_utils.py
Labels: release-note-ignore

#617 Resolve some compiler warnings
  python/setup.py
  python/src/nnabla/_variable.pxd
  src/nbla/function/generic/broadcast.cpp
  src/nbla/function/generic/categorical_cross_entropy.cpp
  src/nbla/function/generic/deconvolution.cpp
  src/nbla/function/generic/depthwise_convolution.cpp
  src/nbla/function/generic/depthwise_deconvolution.cpp
  src/nbla/function/generic/embed.cpp
  src/nbla/function/generic/flip.cpp
  src/nbla/function/generic/inq_affine.cpp
  src/nbla/function/generic/inq_convolution.cpp
  src/nbla/function/generic/max.cpp
  src/nbla/function/generic/min_max_quantize.cpp
  src/nbla/function/generic/prelu.cpp
  src/nbla/function/generic/prune.cpp
  src/nbla/function/generic/random_crop.cpp
  src/nbla/function/generic/random_flip.cpp
  src/nbla/function/generic/slice.cpp
  src/nbla/function/generic/unpooling.cpp
  src/nbla/memory/caching_allocator_with_buckets.cpp
  src/nbla/utils/unfold_to_patches.cpp
Labels: release-note-core

#619 Add random sampling functions.
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/rand_beta.hpp
  include/nbla/function/rand_binomial.hpp
  include/nbla/function/rand_gamma.hpp
  python/src/nnabla/backward_function/rand_beta.py
  python/src/nnabla/backward_function/rand_binomial.py
  python/src/nnabla/backward_function/rand_gamma.py
  python/test/function/test_random_functions.py
  src/nbla/function/generic/rand_beta.cpp
  src/nbla/function/generic/rand_binomial.cpp
  src/nbla/function/generic/rand_gamma.cpp
Labels: release-note-op-layer

#622 Emit error message for an invalid parameter file.
  python/src/nnabla/parameter.py
Labels: release-note-bugfix

#624 Add fused batch normalization for onnx exporter
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#625 Fix pooling family funcs.
  doc/python/command_line_interface.rst
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#626 Update NNabla Converter Support Status Doc.
  doc/python/file_format_converter/Function-Level_Support_Status.rst
Labels: release-note-doc
