Repository sony/nnabla, pull requests merged in 2020-10, with the labels that each got.

#720 Fix the CUDA transpose operation for large N-dimensional inputs.
  python/test/function/test_transpose.py
Labels: release-note-bugfix

#721 Add test case for index of sorting equal values.
  python/test/function/test_sort.py
Labels: release-note-bugfix

#723 Add NNabla NAS to README
  README.md
Labels: release-note-doc

#724 Add RMSpropGraves
  build-tools/code_generator/solver_types.yaml
  build-tools/code_generator/solvers.yaml
  doc/python/api/solver.rst
  include/nbla/solver/rmsprop_graves.hpp
  python/src/nnabla/utils/load.py
  python/src/nnabla/utils/save.py
  python/test/solver/test_rmsprop_graves.py
  src/nbla/solver/generic/rmsprop_graves.cpp
  src/nbla_utils/nnp_impl_create_solver.cpp
Labels: release-note-op-layer

#725 fix forward_all to keep values of all given variables
  python/test/conftest.py
  python/test/test_forward_all.py
  src/nbla/computation_graph/computation_graph.cpp
Labels: release-note-core

#726 Various Enhancements for Doc
  build-tools/code_generator/functions.yaml
  doc/python/api.rst
  doc/python/api/computation_graph.rst
  python/src/nnabla/_computation_graph.pyx
  python/src/nnabla/_variable.pyx
  python/src/nnabla/normalization_functions.py
Labels: release-note-doc

#728 correct gnumakefile link library name
  examples/cpp/mnist_collection/GNUmakefile
  examples/cpp/mnist_runtime/GNUmakefile
  examples/cpp/mnist_training/GNUmakefile
Labels: release-note-build

#729 Update nnabla convert doc at 20200930
  doc/python/file_format_converter/Function-Level_Support_Status.rst
Labels: release-note-doc

#730 Add QuantizeLinear/DequantizeLinear support for onnx Importer.
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-format-converter
