Repository sony/nnabla, pull requests merged in 2020-02, with the labels that each got.

#581 Fix indexing with a boolean nnabla.Variable or NdArray
  python/src/nnabla/_indexing.pyx
  python/test/test_indexing.py
Labels: release-note-op-layer

#585 NHWC Deconvolution (channel_last option)
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/deconvolution.hpp
  python/src/nnabla/parametric_functions.py
  python/test/function/test_deconvolution.py
  src/nbla/function/generic/deconvolution.cpp
  src/nbla/functions.cpp.tmpl
  src/nbla/parametric_functions.cpp
Labels: enhancement, release-note-op-layer

#586 Add patch_correlation function and tests.
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/patch_correlation.hpp
  python/src/nnabla/backward_function/patch_correlation.py
  python/src/nnabla/functions.py
  python/test/function/test_patch_correlation.py
  src/nbla/function/generic/patch_correlation.cpp
Labels: release-note-op-layer

#579 Various fixes for Neural Network Console
  python/src/nnabla/utils/cli/cli.py
  python/src/nnabla/utils/cli/forward.py
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/data_source.py
  python/src/nnabla/utils/data_source_implements.py
  python/src/nnabla/utils/data_source_loader.py
  python/src/nnabla/utils/load.py
Labels: release-note-bugfix

#588 Feature/20200217 fix some issues for snpe
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#589 fix compiler error
  src/nbla_utils/nnp_impl.cpp
Labels: release-note-build

#590 reclaim memory after forward
  src/nbla/function/generic/convolution.cpp
  src/nbla/function/generic/deconvolution.cpp
Labels: release-note-core

#591 feat:add audio_utils and unit test for it
  python/setup.py
  python/src/nnabla/utils/audio_utils/__init__.py
  python/src/nnabla/utils/audio_utils/backend_manager.py
  python/src/nnabla/utils/audio_utils/common.py
  python/src/nnabla/utils/audio_utils/pydub_utils.py
  python/test/utils/test_audio_utils.py
Labels: release-note-core, release-note-utility

#592 Add -dbg prefix when debug build.
  CMakeLists.txt
  build-tools/make/build-with-docker.mk
  build-tools/make/build.mk
  build-tools/make/options.mk
  build-tools/msvc/build_cpplib.bat
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/test.bat
  build-tools/msvc/tools/default_folders.bat
  examples/cpp/CMakeLists.txt
  examples/cpp/cpp_graph/CMakeLists.txt
  examples/cpp/mnist_collection/CMakeLists.txt
  examples/cpp/mnist_collection/GNUmakefile
  examples/cpp/mnist_runtime/CMakeLists.txt
  examples/cpp/mnist_runtime/GNUmakefile
  examples/cpp/mnist_training/CMakeLists.txt
  examples/cpp/mnist_training/GNUmakefile
  include/nbla/defs.hpp
  include/nbla_cli/nbla_infer.hpp
  include/nbla_cli/nbla_train.hpp
  python/setup.py
  src/nbla/CMakeLists.txt
  src/nbla_cli/CMakeLists.txt
  src/nbla_utils/CMakeLists.txt
Labels: release-note-build

#587 Reduce log output
  python/src/nnabla/_nd_array.pyx
Labels: release-note-ignore

#593 Add Cast Gather Support for ONNX Importer.
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-format-converter

#595 Set system name from uname.
  CMakeLists.txt
Labels: release-note-build

#594 Fix code samples and doc in collectives
  doc/python/installation.rst
  python/src/nnabla/communicator.pyx
Labels: release-note-bugfix, release-note-doc
