Repository sony/nnabla, pull requests merged in 2020-06, with the labels that each got.

#646 Support deconv's output_padding for ONNX Exporter.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#645 Fix Broadcast for ONNX Exporter.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#647 Update nnabla convert doc at 20200521
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-doc

#649 Get device-id from local_rank
  python/src/nnabla/utils/load.py
Labels: release-note-utility

#650 Fix bug when reading h5 file in NNP
  python/src/nnabla/utils/get_file_handle.py
Labels: release-note-utility

#651 using sliced data set for monitor, instead of full data set for multi…
  python/src/nnabla/utils/cli/train.py
Labels: release-note-utility

#652 fix nnp to nnp problem with h5
  python/src/nnabla/utils/converter/nnabla/exporter.py
Labels: release-note-utility

#648 Feature/20200529 fix documents
  build-tools/code_generator/functions.yaml
  doc/python/api/models/semantic_segmentation.rst
  doc/python/file_format_converter/compress_network.rst
  doc/python/file_format_converter/file_format_converter.rst
  doc/python/install_on_windows.rst
  doc/python/pip_installation_cuda.rst
  doc/python/tutorial/by_examples.rst
  doc/python/tutorial/graph_converter_for_inference.rst
  doc/python/tutorial/mixed_precision_training.rst
  doc/python/tutorial/python_api.rst
  python/src/nnabla/_nd_array.pyx
  python/src/nnabla/_variable.pyx
  python/src/nnabla/experimental/parametric_function_class/batch_normalization.py
  python/src/nnabla/function_bases.py.tmpl
  python/src/nnabla/functions.py
  python/src/nnabla/grad.py
  python/src/nnabla/initializer.py
  python/src/nnabla/models/object_detection/utils.py
  python/src/nnabla/parametric_functions.py
  tutorial/by_examples.ipynb
  tutorial/python_api.ipynb
Labels: release-note-doc

#653 alleviate test for gamma
  python/test/function/test_random_functions.py
Labels: release-note-ignore

#656 Correct the warp_by_flow documentation
  build-tools/code_generator/functions.yaml
Labels: release-note-doc

#655 Fix Unpooling for SNPE
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-utility

#657 Quantize/DequantizeLinear
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/tutorial/mixed_precision_training.rst
  include/nbla/function/dequantize_linear.hpp
  include/nbla/function/min_max_quantize.hpp
  include/nbla/function/quantize_linear.hpp
  python/src/nnabla/backward_function/dequantize_linear.py
  python/src/nnabla/backward_function/quantize_linear.py
  python/src/nnabla/dtypes.py
  python/src/nnabla/functions.py
  python/src/nnabla/utils/converter/onnx/exporter.py
  python/test/function/test_dequantize_linear.py
  python/test/function/test_min_max_quantize.py
  python/test/function/test_quantize_linear.py
  python/test/function/test_round.py
  src/nbla/function/generic/dequantize_linear.cpp
  src/nbla/function/generic/min_max_quantize.cpp
  src/nbla/function/generic/quantize_linear.cpp
  tutorial/mixed_precision_training.ipynb
Labels: release-note-op-layer

#658 feat: save optimizer states every epoch
  python/src/nnabla/nnabla.conf
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/load.py
Labels: release-note-utility

#661 feat: relocate cg_load info from log to progress.txt and status.json,…
  python/src/nnabla/utils/cli/train.py
Labels: release-note-utility

#662 Fix PReLU for ONNX Exporter.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#664 Add FusedConvolution interface and some enhancements & fixes
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/computation_graph/computation_graph.hpp
  include/nbla/computation_graph/variable.hpp
  include/nbla/function/fused_convolution.hpp
  python/src/nnabla/backward_function/fused_convolution.py
  python/test/communicator/test_sync_batch_normalization.py
  python/test/function/test_binary_activation.py
  python/test/function/test_binary_connect_affine.py
  python/test/function/test_binary_connect_convolution.py
  python/test/function/test_binary_weight_affine.py
  python/test/function/test_binary_weight_convolution.py
  python/test/function/test_ceil.py
  python/test/function/test_clip_grad_by_norm.py
  python/test/function/test_clip_grad_by_value.py
  python/test/function/test_fft.py
  python/test/function/test_fixed_point_quantize.py
  python/test/function/test_floor.py
  python/test/function/test_fused_batch_normalization.py
  python/test/function/test_fused_convolution.py
  python/test/function/test_gelu.py
  python/test/function/test_gru.py
  python/test/function/test_hard_sigmoid.py
  python/test/function/test_hard_tanh.py
  python/test/function/test_ifft.py
  python/test/function/test_inf_nan.py
  python/test/function/test_inq_affine.py
  python/test/function/test_inq_convolution.py
  python/test/function/test_lstm.py
  python/test/function/test_min_max_quantize.py
  python/test/function/test_pow2_quantize.py
  python/test/function/test_prune.py
  python/test/function/test_rnn.py
  python/test/function/test_round.py
  python/test/function/test_sign.py
  python/test/function/test_top_k_data.py
  python/test/function/test_top_k_grad.py
  python/test/nbla_test_utils.py
  src/nbla/computation_graph/computation_graph.cpp
  src/nbla/computation_graph/variable.cpp
  src/nbla/function/generic/convolution.cpp
  src/nbla/function/generic/deconvolution.cpp
  src/nbla/function/generic/depthwise_convolution.cpp
  src/nbla/function/generic/depthwise_deconvolution.cpp
  src/nbla/function/generic/fused_convolution.cpp
Labels: release-note-bugfix

#666 Add **kw args to ref_dequantize_linear and ref_grad_dequantize_linear.
  python/test/function/test_dequantize_linear.py
  python/test/function/test_quantize_linear.py
Labels: release-note-bugfix

#672 Change default build environment from CentOS6 to CentOS7
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-ppc64le
  python/src/nnabla/communicator.pyx
  python/test/function/test_random_functions.py
Labels: release-note-build

#671 feat: save optimizer checkpoint in .h5 format
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/get_file_handle.py
  python/src/nnabla/utils/load.py
Labels: release-note-utility

#669 Change cuDNN algorithm selection method to improve inference performance
  python/src/nnabla/utils/cli/forward.py
Labels: release-note-utility

#673 Fix failure to convert NNabla to tflite.
  python/src/nnabla/utils/converter/tensorflow/exporter.py
Labels: release-note-bugfix
