Repository sony/nnabla, pull requests merged in 2020-08, with the labels that each got.

#697 pass keyword argument to pytest.fixture to fix PytestDeprecationWarning
  python/test/function/test_weight_standardization.py
Labels: release-note-build

#698 Fix the gradient operation when inplaced with output variable.
  src/nbla/function/generic/scatter_nd.cpp
Labels: release-note-bugfix

#699 Check shape length before checking first element.
  python/src/nnabla/utils/nnp_graph.py
Labels: release-note-bugfix

#701 enable .h5 parameter saving.
  build-tools/make/build.mk
  build-tools/make/test_nbla_utils.sh
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.onnx-test-ppc64le
  include/nbla/parametric_functions.hpp
  include/nbla_utils/nnp.hpp
  python/test/function/test_convolution.py
  src/nbla/parametric_functions.cpp
  src/nbla_cli/nbla_train.cpp
  src/nbla_utils/CMakeLists.txt
  src/nbla_utils/nnp_impl.cpp
  src/nbla_utils/nnp_impl.hpp
  src/nbla_utils/nnp_impl_dataset_npy.cpp
  src/nbla_utils/parameters.cpp
  src/nbla_utils/parameters_impl.hpp
  src/nbla_utils/test/test_dataset.cpp
  src/nbla_utils/test/test_gen_loop_control_cases.py
  src/nbla_utils/test/test_generate_nnp.py
  src/nbla_utils/test/test_load_save.cpp
  src/nbla_utils/test/test_load_save_parameters.cpp
  src/nbla_utils/test/test_npy_files.py
Labels: release-note-utility

#702 Fix normalization with 16bit integer data.
  python/src/nnabla/utils/data_source_implements.py
  python/src/nnabla/utils/data_source_loader.py
Labels: release-note-utility

#703 correct nnabla version number
  doc/requirements.txt
Labels: release-note-ignore

#705 feat: use multiprocess to create cache and add the test file of create_cache
  python/src/nnabla/utils/cli/conv_dataset.py
  python/src/nnabla/utils/create_cache.py
  python/src/nnabla/utils/data_source_implements.py
  python/test/utils/test_create_cache.py
Labels: release-note-utility

#706 Improve NNabla converter doc.
  doc/python/file_format_converter/file_format_converter.rst
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.onnx-test-ppc64le
  python/requirements.txt
Labels: release-note-doc
