Repository sony/nnabla, pull requests merged in 2020-05, with the labels that each got.

#627 Refactor image utils
  docker/development/Dockerfile.onnx-test
  python/setup.py
  python/src/nnabla/utils/data_source_loader.py
  python/src/nnabla/utils/image_utils/__init__.py
  python/src/nnabla/utils/image_utils/backend_events/__init__.py
  python/src/nnabla/utils/image_utils/backend_events/common.py
  python/src/nnabla/utils/image_utils/backend_events/cv2_backend.py
  python/src/nnabla/utils/image_utils/backend_events/dicom_backend.py
  python/src/nnabla/utils/image_utils/backend_events/image_utils_backend.py
  python/src/nnabla/utils/image_utils/backend_events/pil_backend.py
  python/src/nnabla/utils/image_utils/backend_events/pypng_backend.py
  python/src/nnabla/utils/image_utils/backend_manager.py
  python/src/nnabla/utils/image_utils/cv2_utils.py
  python/src/nnabla/utils/image_utils/pil_utils.py
  python/src/nnabla/utils/image_utils/pypng_utils.py
  python/test/utils/test_image_utils.py
Labels: release-note-utility

#632 Restore VERSION to 1.8.0.dev1
  VERSION.txt
Labels: release-note-ignore

#633 Fix image_utils failed to use another backend.
  python/src/nnabla/utils/image_utils/backend_events/cv2_backend.py
  python/src/nnabla/utils/image_utils/backend_events/image_utils_backend.py
  python/src/nnabla/utils/image_utils/backend_events/pil_backend.py
  python/src/nnabla/utils/image_utils/backend_events/pypng_backend.py
Labels: release-note-utility

#635 Fix use_up_to keyword for VGG16
  python/src/nnabla/models/imagenet/vgg.py
Labels: release-note-bugfix

#637 feat: measure cpu/gpu load & write to status.json when psutil, pynvml…
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/progress.py
Labels: release-note-utility

#638 update devtoolset package version. update url of yum repository
  docker/development/Dockerfile.build
Labels: release-note-build

#639 remove thread-based watchdog for allreduce
  python/src/nnabla/utils/cli/train.py
Labels: release-note-utility

#641 Interpolation with half_pixel and half_pixel_for_nn
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/interpolate.hpp
  python/src/nnabla/backward_function/interpolate.py
  python/src/nnabla/functions.py
  python/src/nnabla/utils/converter/onnx/exporter.py
  python/test/function/test_interpolate.py
  src/nbla/function/generic/interpolate.cpp
Labels: release-note-op-layer

#642 Fix log double backward
  python/src/nnabla/backward_function/log.py
Labels: release-note-bugfix

#643 Add deconvolution output padding option.
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  examples/cpp/mnist_collection/dcgan_training.hpp
  include/nbla/function/deconvolution.hpp
  include/nbla/functions.hpp.tmpl
  include/nbla/parametric_functions.hpp
  python/src/nnabla/backward_function/deconvolution.py
  python/src/nnabla/parametric_functions.py
  python/test/function/refs.py
  python/test/function/test_deconvolution.py
  src/nbla/function/generic/deconvolution.cpp
  src/nbla/functions.cpp.tmpl
  src/nbla/parametric_functions.cpp
Labels: release-note-op-layer

#644 Change align_corners to False as default and add warning notes
  python/src/nnabla/functions.py
Labels: release-note-break-compat
