Repository sony/nnabla, pull requests merged in 2020-03, with the labels that each got.

#601 Add AddN and MulN functions
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/add_n.hpp
  include/nbla/function/mul_n.hpp
  python/src/nnabla/backward_function/add_n.py
  python/src/nnabla/backward_function/mul_n.py
  python/test/function/test_add_n.py
  python/test/function/test_mul_n.py
  src/nbla/function/generic/add_n.cpp
  src/nbla/function/generic/mul_n.cpp
Labels: release-note-op-layer

#602 update cuda-cudnn table for v1.6.0
  doc/python/pip_installation_cuda.rst
Labels: release-note-doc

#574 Add keyword "lastfeature" to nnabla models
  python/src/nnabla/models/imagenet/densenet.py
  python/src/nnabla/models/imagenet/mobilenet.py
  python/src/nnabla/models/imagenet/nin.py
  python/src/nnabla/models/imagenet/resnet.py
  python/src/nnabla/models/imagenet/resnext.py
  python/src/nnabla/models/imagenet/senet.py
  python/src/nnabla/models/imagenet/shufflenet.py
  python/src/nnabla/models/imagenet/squeezenet.py
  python/src/nnabla/models/imagenet/vgg.py
  python/test/models/test_imagenet.py
Labels: release-note-nnabla-models

#603 Fix MaxPooling and PReLU
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#605 Add Unpooling support in opset greater than 9.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#606 Fix load_save_parameter problem by adding ios::binary
  build-tools/msvc/build_cpplib.bat
  build-tools/msvc/test_nbla.bat
  src/nbla_utils/CMakeLists.txt
  src/nbla_utils/nnp_impl.cpp
  src/nbla_utils/parameters.cpp
  src/nbla_utils/test/test_load_save_parameters.cpp
Labels: release-note-bugfix

#607 Refectoring
  examples/cpp/mnist_runtime/save_nnp_classification.py
  examples/cpp/nbla_train/create_initialized_model.py
  examples/cpp/nbla_train/create_mnist_cache.py
  python/benchmark/function/function_benchmark.py
  python/src/nnabla/backward_function/add_n.py
  python/src/nnabla/backward_function/batch_det.py
  python/src/nnabla/backward_function/batch_inv.py
  python/src/nnabla/backward_function/min_max_quantize.py
  python/src/nnabla/backward_function/mul_n.py
  python/src/nnabla/grad.py
  python/src/nnabla/logger.py
  python/src/nnabla/models/imagenet/alexnet.py
  python/src/nnabla/models/imagenet/base.py
  python/src/nnabla/models/imagenet/googlenet.py
  python/src/nnabla/models/imagenet/inception.py
  python/src/nnabla/models/imagenet/mobilenet.py
  python/src/nnabla/models/object_detection/base.py
  python/src/nnabla/models/semantic_segmentation/base.py
  python/src/nnabla/utils/audio_utils/__init__.py
  python/src/nnabla/utils/audio_utils/common.py
  python/src/nnabla/utils/cli/compare_with_cpu.py
  python/src/nnabla/utils/data_source.py
  python/src/nnabla/utils/data_source_loader.py
  python/src/nnabla/utils/image_utils/__init__.py
  python/src/nnabla/utils/load.py
  python/src/nnabla/utils/save.py
  python/test/nbla_test_utils.py
  python/test/utils/learning_rate_scheduler/learning_rate_scheduler_test_utils.py
  python/test/utils/test_graph_converters/ref_graphs/helper.py
  tutorial/caltech101_data.py
Labels: release-note-ignore

#609 Correct spells
  python/test/test_grad.py
Labels: release-note-ignore

#610 RandomErase Function
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  build-tools/code_generator/generate.py
  build-tools/code_generator/utils/type_conv.py
  doc/python/api/function.rst
  include/nbla/function/random_erase.hpp
  python/src/nnabla/backward_function/random_erase.py
  python/test/function/test_random_erase.py
  src/nbla/function/generic/random_erase.cpp
  src/nbla_utils/nnp_impl_create_function.cpp.tmpl
Labels: release-note-op-layer
