Repository sony/nnabla, pull requests merged in 2021-03, with the labels that each got.

#815 Memory optimization for SpectralNorm
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/spectral_norm.hpp
  python/src/nnabla/backward_function/spectral_norm.py
  python/src/nnabla/parametric_functions.py
  python/test/function/test_spectral_norm.py
  python/test/test_parametric_functions.py
  src/nbla/function/generic/spectral_norm.cpp
Labels: release-note-op-layer

#817 NNP Network Refactor
  doc/python/api.rst
  doc/python/api/graph_def.rst
  doc/python/api/module.rst
  python/src/nnabla/core/graph_def.py
  python/src/nnabla/core/graph_optimizer.py
  python/src/nnabla/core/module.py
  python/src/nnabla/core/variable_batch_size.py
  python/src/nnabla/function.pyx.tmpl
  python/src/nnabla/parameter.py
  python/src/nnabla/utils/cli/conv_dataset.py
  python/src/nnabla/utils/cli/forward.py
  python/src/nnabla/utils/cli/profile.py
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/create_cache.py
  python/src/nnabla/utils/get_file_handle.py
  python/src/nnabla/utils/load.py
  python/src/nnabla/utils/nnp_graph.py
  python/src/nnabla/utils/save.py
  python/test/core/generate_nntxt_testcase.py
  python/test/core/helper.py
  python/test/core/legacy_expander.py
  python/test/core/legacy_get_file_handle.py
  python/test/core/legacy_load.py
  python/test/core/legacy_network.py
  python/test/core/legacy_nnp_graph.py
  python/test/core/nntxt.py
  python/test/core/test_load.py
  python/test/core/test_module.py
  python/test/core/test_nnp_graph.py
  python/test/core/test_parameter_load_save.py
  python/test/core/test_variable_batch_size.py
  python/test/test_nnp_graph.py
  python/test/utils/test_create_cache.py
Labels: release-note-utility

#818 add dockerfile for armhf
  docker/py37/Dockerfile.armhf
Labels: release-note-ignore

#819 Fix async copy in NNabla::ones and zeros
  src/nbla/singleton_manager.cpp
  src/nbla/synced_array.cpp
Labels: release-note-bugfix

#821 Support conversion tflite to nnabla.
  doc/python/file_format_converter/file_format_converter.rst
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/converter/commands.py
  python/src/nnabla/utils/converter/setup.py
  python/src/nnabla/utils/converter/supported_info.py
  python/src/nnabla/utils/converter/tensorflow/__init__.py
  python/src/nnabla/utils/converter/tensorflow/importer.py
Labels: release-note-format-converter

#823 Fix code typo.
  python/src/nnabla/utils/converter/nnabla/exporter.py
Labels: release-note-ignore

#822 Support comment columns in dataset CSV files
  python/src/nnabla/utils/cli/forward.py
  python/src/nnabla/utils/create_cache.py
  python/src/nnabla/utils/data_source_implements.py
  python/src/nnabla/utils/data_source_loader.py
Labels: release-note-utility

#824 fix: solve the error that pynvml cannot solve the path to nvml.dll on windows
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/nvml.py
Labels: release-note-bugfix

#825 Add OOC option to nnabla_cli train
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/cli/utility.py
Labels: release-note-utility

#826 Fix nnabla Nan error in training.
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/load.py
Labels: release-note-bugfix

#827 Add feature for nnabla_cli
  python/src/nnabla/nnabla.conf
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/load.py
Labels: release-note-utility

#829 Fix to support utf-8 enconding with BOM
  python/src/nnabla/utils/cli/forward.py
  python/src/nnabla/utils/create_cache.py
  python/src/nnabla/utils/data_source_implements.py
  python/src/nnabla/utils/data_source_loader.py
  python/src/nnabla/utils/load.py
Labels: release-note-utility

#828 Support BatchNorm1d for ONNX importer.
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-utility

#830 Increase gpu speed threshold
  .rocro.yml
  build-tools/tox.ini
  python/src/nnabla/nnabla.conf
  python/src/nnabla/utils/cli/train.py
  python/src/nnabla/utils/get_file_handle.py
  python/src/nnabla/utils/load.py
  python/test/cpp/test_mnist_runtime.py
  python/test/function/test_vat_noise.py
Labels: release-note-bugfix

#831 improve grad() with filter out dead parameters
  python/src/nnabla/grad.py
Labels: release-note-bugfix

#832 fix coding error for mutex setting
  include/nbla/computation_graph/computation_graph.hpp
  src/nbla/computation_graph/computation_graph.cpp
Labels: release-note-bugfix

#833 fix -1 axis error and grad not found
  python/src/nnabla/core/graph_def.py
  python/src/nnabla/utils/load.py
Labels: release-note-bugfix

#834 Remove redundant input for some funcs.
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-bugfix

#836 Update nnabla converter document for release nnabla
  doc/python/file_format_converter/Function-Level_Support_Status.rst
Labels: release-note-doc

#837 Support export to tensorflow frozen graph again.
  doc/python/command_line_interface.rst
  doc/python/file_format_converter/file_format_converter.rst
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/converter/commands.py
  python/src/nnabla/utils/converter/supported_info.py
  python/src/nnabla/utils/converter/tensorflow/exporter.py
Labels: release-note-format-converter

#838 Fix issues of the converter.
  python/src/nnabla/utils/converter/nnabla/importer.py
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-bugfix

#839 fix nnp refactor memory problem
  python/src/nnabla/utils/cli/train.py
Labels: release-note-bugfix

#840 Bugfix: grad computation of linear functions
  python/src/nnabla/backward_function/backward_function.py
  python/test/test_grad.py
Labels: release-note-bugfix

#841 remove inplace_grad() related code
  python/src/nnabla/utils/cli/profile.py
Labels: release-note-bugfix

#842 Update nnabla converter document for release nnabla
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-doc

#844 Update version
  doc/requirements.txt
Labels: release-note-ignore

#845 Fix numerical instability for log_sigmoid and softplus
  include/nbla/function/log_sigmoid.hpp
  include/nbla/function/softplus.hpp
Labels: release-note-bugfix
