Repository sony/nnabla, pull requests merged in 2021-07, with the labels that each got.

#900 Support variadic inputs of nbla::functions::concatenate()
  examples/cpp/mnist_collection/mnist_data.hpp
  examples/cpp/mnist_collection/vae_training.hpp
  include/nbla/functions.hpp.tmpl
  src/nbla/functions.cpp.tmpl
  src/nbla/test/test_variadic_input.cpp
Labels: release-note-core

#901 Add unitest for graph/parameters issue
  python/src/nnabla/core/graph_def.py
  python/src/nnabla/utils/get_file_handle.py
  python/test/core/test_module.py
  python/test/core/test_nnp_graph.py
Labels: release-note-bugfix

#902 Fix generating tensorboard writer related document problem
  docker/development/Dockerfile.document
Labels: release-note-doc

#903 fix indexing leaf variable problem
  python/src/nnabla/_variable.pyx
  python/test/test_variable.py
Labels: release-note-bugfix

#904 fix parameter error for graph viewer
  python/src/nnabla/experimental/viewers.py
Labels: release-note-bugfix

#905 update document for randint
  build-tools/code_generator/functions.yaml
Labels: release-note-doc

#906 refactor:remove redundant image backend switch
  python/src/nnabla/utils/data_source_loader.py
Labels: release-note-utility

#907 Implement custom module nvml to replace pynvml
  build-tools/msvc/tools/python_env.bat
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/nvml.py
  python/test/utils/test_nvml.py
Labels: release-note-utility

#911 Higher-order gradients for normalization functions
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/spectral_norm.hpp
  python/src/nnabla/backward_function/group_normalization.py
  python/src/nnabla/backward_function/instance_normalization.py
  python/src/nnabla/backward_function/layer_normalization.py
  python/src/nnabla/backward_function/norm.py
  python/src/nnabla/backward_function/norm_normalization.py
  python/src/nnabla/backward_function/spectral_norm.py
  python/src/nnabla/backward_function/sum.py
  python/src/nnabla/backward_function/tensor_normalization.py
  python/src/nnabla/backward_function/weight_normalization.py
  python/src/nnabla/backward_function/weight_standardization.py
  python/src/nnabla/functions.py
  python/test/function/test_group_normalization.py
  python/test/function/test_instance_normalization.py
  python/test/function/test_layer_normalization.py
  python/test/function/test_norm.py
  python/test/function/test_norm_normalization.py
  python/test/function/test_spectral_norm.py
  python/test/function/test_weight_normalization.py
  python/test/function/test_weight_standardization.py
  python/test/nbla_test_utils.py
  src/nbla/function/generic/spectral_norm.cpp
Labels: release-note-op-layer

#912 change image_utils imread behavior for pillow backend compatibility
  python/src/nnabla/utils/image_utils/backend_events/pil_backend.py
Labels: release-note-build

#913 support nnabla to export spectralnorm in onnx
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#915 Improve dropout explanation and add searchsorted to document
  doc/python/api/function.rst
  python/src/nnabla/functions.py
Labels: release-note-doc

#917 Bugfix: fix nn.grad for floating variables
  python/src/nnabla/grad.py
  python/test/test_grad.py
Labels: release-note-bugfix

#918 Add a quantized tflite converter to export nnp to int8 tflite
  doc/python/command_line_interface.rst
  doc/python/file_format_converter/INT8_TFLite_Support_Status.rst
  doc/python/file_format_converter/file_format_converter.rst
  doc/support_status.rst
  docker/development/Dockerfile.auto-format
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/converter/commands.py
  python/src/nnabla/utils/converter/tflite/exporter.py
  python/src/nnabla/utils/converter/tflite/quantized_converter.py
Labels: release-note-format-converter

#920 temporarily comment out a test which cause randomly crash.
  python/test/test_graph.py
Labels: release-note-build

#921 support nnabla to export weightstandardization & instancenormalization & layernormalization in onnx
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#922 Fix build without http_proxy
  build-tools/make/options.mk
Labels: release-note-build

#923 Properly close file handlers at exception
  python/src/nnabla/utils/get_file_handle.py
  python/test/core/test_get_file_handle.py
Labels: release-note-bugfix

#924 Fix duplicate calls in forward_all
  .gitignore
  python/test/test_forward_all.py
  src/nbla/computation_graph/computation_graph.cpp
Labels: release-note-bugfix

#925 support weightnormalization exporter
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#926 Add roi_align function and tests
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/roi_align.hpp
  python/src/nnabla/backward_function/roi_align.py
  python/test/function/test_roi_align.py
  src/nbla/function/generic/roi_align.cpp
Labels: release-note-core

#928 CI: Restructure dockerfile directory
  build-tools/make/options.mk
  docker/development/Dockerfile.android
  docker/development/Dockerfile.android-test
  docker/development/Dockerfile.auto-format
  docker/development/Dockerfile.build-armhf
  docker/development/Dockerfile.document
  docker/development/Dockerfile.nnabla-test
  docker/development/Dockerfile.nnabla-test-armhf
  docker/development/Dockerfile.nnabla-test-ppc64le
  docker/release/Dockerfile.py36
  docker/release/Dockerfile.py37
  docker/release/Dockerfile.py37-armhf
  docker/release/Dockerfile.py38
Labels: release-note-build

#929 modify contents of Math section and Array Manipulation
  doc/python/api/function.rst
Labels: release-note-doc
