Repository sony/nnabla, pull requests merged in 2021-02, with the labels that each got.

#787 Update for ARM build
  build-tools/make/test_nbla_utils.sh
  build-tools/msvc/tools/python_env_cleanup.bat
  docker/development/Dockerfile.build-armhf
  docker/development/Dockerfile.onnx-test-armhf
  python/setup.py
Labels: release-note-build

#789 Update nnabla converter document for release nnabla
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-doc

#790 Fix error in using VGG
  python/src/nnabla/models/imagenet/base.py
Labels: release-note-bugfix

#791 add error message when parameter is illegal
  python/src/nnabla/_nd_array.pyx
Labels: release-note-core

#792 Constant mode optoin for F.random_shift
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/random_shift.hpp
  python/test/function/test_random_shift.py
  src/nbla/function/generic/random_shift.cpp
Labels: release-note-op-layer

#794 Remove ONNX from NNabla requirement and Update document.
  build-tools/make/build-with-docker.mk
  doc/python/file_format_converter/file_format_converter.rst
  docker/development/Dockerfile.nnabla-test
  docker/development/Dockerfile.nnabla-test-armhf
  docker/development/Dockerfile.nnabla-test-ppc64le
  docker/development/Dockerfile.tf-test
  python/requirements.txt
  python/setup.py
  python/src/nnabla/utils/converter/setup.py
Labels: release-note-build

#795 Attach initializer info to Variable.
  python/src/nnabla/parameter.py
  python/src/nnabla/utils/save.py
Labels: release-note-utility

#796 fix link error for extra NBLA_API
  include/nbla/memory/virtual_caching_allocator.hpp
Labels: release-note-build

#799 Pad memory optimization and add repeat mode
  build-tools/code_generator/functions.yaml
  include/nbla/function/pad.hpp
  python/test/function/test_pad.py
  src/nbla/function/generic/pad.cpp
Labels: release-note-op-layer

#800 Optimize normalization functions implementation
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  examples/cpp/cpp_graph/main.cpp
  include/nbla/function/batch_normalization.hpp
  include/nbla/function/group_normalization.hpp
  include/nbla/function/instance_normalization.hpp
  include/nbla/function/layer_normalization.hpp
  include/nbla/function/sync_batch_normalization.hpp
  include/nbla/function/tensor_normalization.hpp
  include/nbla/function/weight_standardization.hpp
  python/src/nnabla/backward_function/batch_normalization.py
  python/src/nnabla/backward_function/group_normalization.py
  python/src/nnabla/backward_function/instance_normalization.py
  python/src/nnabla/backward_function/layer_normalization.py
  python/src/nnabla/backward_function/tensor_normalization.py
  python/src/nnabla/backward_function/weight_standardization.py
  python/src/nnabla/experimental/graph_converters/batch_norm_batchstat.py
  python/src/nnabla/experimental/graph_converters/channel_first.py
  python/src/nnabla/experimental/graph_converters/channel_last.py
  python/src/nnabla/normalization_functions.py
  python/test/function/test_batch_normalization.py
  python/test/function/test_group_normalization.py
  python/test/function/test_instance_normalization.py
  python/test/function/test_layer_normalization.py
  python/test/function/test_weight_standardization.py
  python/test/nbla_test_utils.py
  python/test/test_parametric_functions.py
  src/nbla/function/generic/batch_normalization.cpp
  src/nbla/function/generic/fused_batch_normalization.cpp
  src/nbla/function/generic/fused_convolution.cpp
  src/nbla/function/generic/group_normalization.cpp
  src/nbla/function/generic/instance_normalization.cpp
  src/nbla/function/generic/layer_normalization.cpp
  src/nbla/function/generic/tensor_normalization.cpp
  src/nbla/function/generic/weight_standardization.cpp
  src/nbla/functions.cpp.tmpl
  src/nbla/parametric_functions.cpp
Labels: release-note-op-layer

#801 Add Citation for Arxiv Paper
  README.md
Labels: release-note-doc

#804 fix comment error in .bat
  build-tools/msvc/tools/python_env_cleanup.bat
Labels: release-note-ignore

#802 Memory optimization for STFT/iSTFT
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/istft.hpp
  include/nbla/function/stft.hpp
  python/src/nnabla/backward_function/istft.py
  python/src/nnabla/backward_function/stft.py
  python/src/nnabla/functions.py
  python/test/function/test_stft.py
  src/nbla/function/generic/istft.cpp
  src/nbla/function/generic/stft.cpp
Labels: release-note-op-layer

#803 Negative axis support for nnabla functions
  python/src/nnabla/backward_function/log_softmax.py
  python/src/nnabla/backward_function/softmax.py
  python/test/function/test_broadcast_to.py
  python/test/function/test_categorical_cross_entropy.py
  python/test/function/test_celu.py
  python/test/function/test_clip_by_norm.py
  python/test/function/test_concatenate.py
  python/test/function/test_confusion_matrix.py
  python/test/function/test_crelu.py
  python/test/function/test_flip.py
  python/test/function/test_gather.py
  python/test/function/test_log_softmax.py
  python/test/function/test_mean_subtraction.py
  python/test/function/test_norm.py
  python/test/function/test_softmax.py
  python/test/function/test_softmax_cross_entropy.py
  python/test/function/test_sort.py
  python/test/function/test_split.py
  python/test/function/test_top_k_data.py
  python/test/function/test_top_k_grad.py
  python/test/function/test_top_n_error.py
  src/nbla/function/generic/categorical_cross_entropy.cpp
  src/nbla/function/generic/celu.cpp
  src/nbla/function/generic/concatenate.cpp
  src/nbla/function/generic/confusion_matrix.cpp
  src/nbla/function/generic/crelu.cpp
  src/nbla/function/generic/flip.cpp
  src/nbla/function/generic/gather.cpp
  src/nbla/function/generic/log_softmax.cpp
  src/nbla/function/generic/mean_subtraction.cpp
  src/nbla/function/generic/softmax.cpp
  src/nbla/function/generic/softmax_cross_entropy.cpp
  src/nbla/function/generic/split.cpp
  src/nbla/function/generic/stack.cpp
  src/nbla/function/generic/sum.cpp
  src/nbla/function/generic/top_k_data.cpp
  src/nbla/function/generic/top_k_grad.cpp
  src/nbla/function/generic/top_n_error.cpp
  src/nbla/function/generic/transpose.cpp
Labels: enhancement

#807 Fix generate nnb config file error
  python/src/nnabla/utils/cli/convert.py
Labels: release-note-bugfix

#808 pynvml cannot solve the path to nvml.dll on windows
  python/src/nnabla/utils/cli/utility.py
Labels: release-note-bugfix

#809 Deformable Convolution
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  doc/python/api/parametric_function.rst
  include/nbla/function/deformable_convolution.hpp
  include/nbla/utils/deformable-im2col-internal.hpp
  python/src/nnabla/backward_function/deformable_convolution.py
  python/src/nnabla/parametric_functions.py
  python/test/function/refs.py
  python/test/function/test_deformable_convolution.py
  python/test/test_parametric_functions.py
  src/nbla/function/generic/deformable_convolution.cpp
  src/nbla/utils/deformable-im2col-internal.cpp
Labels: release-note-op-layer

#811 Limit numpy version to 1.19.5
  docker/development/Dockerfile.build
  python/requirements.txt
Labels: release-note-build

#812 Fix a bug in function reference count
  src/nbla/computation_graph/variable.cpp
Labels: release-note-bugfix
