Repository sony/nnabla, pull requests merged in 2021-06, with the labels that each got.

#886 Allow parameter load and save in module
  python/src/nnabla/core/module.py
  python/test/core/test_parameter_load_save.py
Labels: release-note-utility

#885 Pass name attribute to parameter Variables
  python/src/nnabla/parameter.py
  python/test/test_parameter.py
Labels: release-note-core

#887 refactor: change audio_utils load resource behavior
  python/src/nnabla/utils/audio_utils/__init__.py
  python/src/nnabla/utils/audio_utils/common.py
  python/src/nnabla/utils/audio_utils/pydub_utils.py
  python/src/nnabla/utils/data_source_loader.py
  python/src/nnabla/utils/image_utils/backend_events/image_utils_backend.py
  python/test/utils/test_audio_utils.py
  python/test/utils/test_data_source_loader.py
Labels: release-note-utility

#888 fix error when save network with F.mean()
  python/src/nnabla/core/variable_batch_size.py
  python/test/core/test_variable_batch_size.py
  python/test/utils/test_graph_converters/ref_graphs/resnets.py
Labels: release-note-utility

#889 support make nnabla-check-copyright
  build-tools/code_formatter/copyright_checker.py
  build-tools/make/build-with-docker.mk
  build-tools/make/build.mk
  docker/development/Dockerfile.auto-format
Labels: release-note-build

#890 Bug fix of fused binary operator
  python/test/function/test_transform_binary.py
Labels: release-note-bugfix

#891 fix: pynvml.nvml has no attribute nvml_lib
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/nvml.py
Labels: release-note-utility

#894 Fix type comparison from ndarray to list in ONNX Exporter
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-bugfix

#895 Allow additional options to commands that use network
  build-tools/make/build.mk
  build-tools/make/options.mk
  build-tools/msvc/test.bat
  build-tools/msvc/tools/python_env.bat
  docker/development/Dockerfile.android
  docker/development/Dockerfile.android-test
  docker/development/Dockerfile.auto-format
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-armhf
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.document
  docker/development/Dockerfile.nnabla-test
  docker/development/Dockerfile.nnabla-test-armhf
  docker/development/Dockerfile.nnabla-test-ppc64le
  docker/py36/Dockerfile
  docker/py37/Dockerfile
  docker/py37/Dockerfile.armhf
  docker/py38/Dockerfile
  docker/runtime/Dockerfile
  docker/tutorial/Dockerfile
  third_party/CMakeLists.txt
Labels: release-note-build

#896 Update progress when creating cache
  python/src/nnabla/utils/create_cache.py
Labels: release-note-utility

#897 install flatbuffer compiler for new tflite converter
  doc/python/file_format_converter/file_format_converter.rst
  docker/py36/Dockerfile
  docker/py37/Dockerfile
Labels: release-note-bugfix
