Repository sony/nnabla, pull requests merged in 2021-08, with the labels that each got.

#932 Inplace methods reverts to using inplace=False
  python/src/nnabla/_variable.pyx
Labels: release-note-break-compat

#934 add dot & matmul operator
  doc/python/api/function.rst
  python/src/nnabla/_arithmetic_ops.pxd
  python/src/nnabla/_arithmetic_ops.pyx
  python/src/nnabla/_nd_array.pyx
  python/src/nnabla/_variable.pyx
  python/src/nnabla/functions.py
  python/src/nnabla/numpy_compat_functions.py
  python/test/nbla_test_function_network.py
  python/test/test_matmul_ops.py
  python/test/test_numpy_compat_functions.py
Labels: release-note-op-layer

#935 support ceil_mode for onnx exporter
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-format-converter

#936 fix race condition for data iterator with cache dataset
  python/src/nnabla/utils/data_source_implements.py
  python/test/utils/conftest.py
  python/test/utils/test_sliced_data_iterator.py
Labels: release-note-bugfix

#937 Skip some tests on 32bit system.
  build-tools/make/build.mk
  python/test/function/test_embed.py
Labels: release-note-build

#939 improve extension document
  doc/python/api/ext.rst
Labels: release-note-doc

#938 Fix APT_OPTS for runtime dockerfiles
  docker/runtime/Dockerfile
Labels: release-note-build

#940 Add missing function modifiers to doc
  doc/python/api/experimentals/graph_converters.rst
  python/src/nnabla/experimental/graph_converters/identity.py
  python/src/nnabla/experimental/graph_converters/no_grad.py
Labels: release-note-doc

#941 Support multiple callback
  python/src/nnabla/utils/callback.py
Labels: release-note-utility

#942 feat: reduce create cache log and print every 5%
  python/src/nnabla/utils/create_cache.py
  python/src/nnabla/utils/load.py
Labels: release-note-utility

#943 improve nntxt's annotation
  python/test/core/nntxt.py
Labels: release-note-ignore

#945 Ignore label less than 0 in cross entropy
  build-tools/code_generator/functions.yaml
  python/test/function/test_categorical_cross_entropy.py
  python/test/function/test_softmax_cross_entropy.py
  src/nbla/function/generic/categorical_cross_entropy.cpp
  src/nbla/function/generic/softmax_cross_entropy.cpp
Labels: release-note-op-layer

#947 fix: update onnx_opset_tensorrt, use opset11 version
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-format-converter

#948 Support p=0 for dropout function
  python/test/function/test_dropout.py
  src/nbla/function/generic/dropout.cpp
Labels: release-note-op-layer

#949 fix status 9 error
  python/test/utils/test_sliced_data_iterator.py
Labels: release-note-bugfix

#950 Make inplace option in most of Function operations obsolete
  build-tools/code_generator/functions.yaml
  include/nbla/function/add2.hpp
  include/nbla/function/add_scalar.hpp
  include/nbla/function/bc_add2.hpp
  include/nbla/function/leaky_relu.hpp
  include/nbla/function/mul_scalar.hpp
  include/nbla/function/random_erase.hpp
  include/nbla/function/relu.hpp
  include/nbla/function/sub2.hpp
  python/src/nnabla/_nd_array.pyx
  python/src/nnabla/_variable.pyx
  python/test/test_grad.py
  python/test/test_graph.py
  src/nbla/function/generic/add2.cpp
  src/nbla/function/generic/leaky_relu.cpp
  src/nbla/function/generic/random_erase.cpp
  src/nbla/function/generic/relu.cpp
Labels: release-note-break-compat

#953 Fix doc error
  doc/python/tutorial/python_api.rst
  python/src/nnabla/parametric_functions.py
  tutorial/python_api.ipynb
Labels: release-note-doc

#957 Reduce create_cache log for s3 dataset
  python/src/nnabla/utils/data_source.py
Labels: release-note-utility

#956 insert download import
  python/src/nnabla/utils/data_source_loader.py
Labels: release-note-ignore
