Repository sony/nnabla, pull requests merged in 2021-01, with the labels that each got.

#772 support multi-thread training
  include/nbla/global_context.hpp
  include/nbla/memory/allocator.hpp
  src/nbla/global_context.cpp
  src/nbla/init.cpp.tmpl
  src/nbla/memory/allocator.cpp
  src/nbla/memory/caching_allocator_with_buckets.cpp
  src/nbla/test/test_multi_thread_training.cpp
Labels: release-note-bugfix

#773 Fix code typo
  python/src/nnabla/utils/cli/convert.py
Labels: release-note-bugfix

#774 Add document and trivial modification for using tensorboard
  doc/python/api/experimental.rst
  doc/python/api/experimentals/tb_graph_writer.rst
  doc/python/api/experimentals/tb_graph_writer_files/graph.PNG
  doc/python/api/experimentals/tb_graph_writer_files/histogram.PNG
  doc/python/api/experimentals/tb_graph_writer_files/scalar.PNG
  docker/development/Dockerfile.document
  python/src/nnabla/experimental/tb_graph_writer.py
  python/test/experimental/test_tb_graph_writer.py
Labels: release-note-doc

#775 update gnumakefile in examples/cpp
  examples/cpp/mnist_runtime/GNUmakefile
  examples/cpp/mnist_runtime/README.md
Labels: release-note-bugfix

#776 Update nnabla convert doc at 20201228
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-doc

#771 add NNabla version arg for dockerfile
  docker/py36/Dockerfile
  docker/py37/Dockerfile
  docker/py38/Dockerfile
Labels: release-note-ignore

#779 Support tf2.x for nnabla converter.
  CMakeLists.txt
  doc/python/command_line_interface.rst
  doc/python/file_format_converter/file_format_converter.rst
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/cli/optimize_pb_model.py
  python/src/nnabla/utils/converter/commands.py
  python/src/nnabla/utils/converter/onnx/exporter.py
  python/src/nnabla/utils/converter/onnx/importer.py
  python/src/nnabla/utils/converter/setup.py
  python/src/nnabla/utils/converter/supported_info.py
  python/src/nnabla/utils/converter/tensorflow/exporter.py
  python/src/nnabla/utils/converter/tensorflow/importer.py
Labels: release-note-format-converter

#780 support the file-like object in nnploader
  python/src/nnabla/utils/nnp_graph.py
  python/test/test_nnp_graph.py
Labels: release-note-utility

#781 Enable cache option for slice method of DataItertor.
  python/src/nnabla/utils/data_iterator.py
Labels: release-note-utility

#782 Fix test shift error
  python/test/function/test_shift.py
Labels: release-note-build

#784 fix window build bug
  build-tools/msvc/build_cpplib.bat
Labels: release-note-build
