Repository sony/nnabla, pull requests merged in 2021-12, with the labels that each got.

#994 Improve recomputation API
  .gitignore
  include/nbla/recompute.hpp
  python/setup.py
  python/src/nnabla/__init__.py
  python/src/nnabla/recompute.pxd
  python/src/nnabla/recompute.pyx
  python/test/conftest.py
  python/test/test_graph.py
  src/nbla/computation_graph/variable.cpp
  src/nbla/recompute.cpp
Labels: release-note-utility

#995 Add linspace function
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/linspace.hpp
  python/src/nnabla/backward_function/linspace.py
  python/src/nnabla/functions.py
  python/test/function/test_linspace.py
  src/nbla/function/generic/linspace.cpp
Labels: release-note-op-layer

#996 Update nnabla convert doc at 20211126
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-doc

#997 Add PYTEST_OPTS for pytest parallel execution
  build-tools/make/build.mk
  build-tools/make/options.mk
  build-tools/msvc/test.bat
  python/pytest.ini
Labels: release-note-build

#998 Fix recomputation for the function which requires output data for backward computation
  python/test/test_graph.py
  src/nbla/computation_graph/variable.cpp
Labels: release-note-bugfix

#999 Make ISTFT consistent with PyTorch implementation (NOLA condition)
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  build-tools/msvc/tools/python_env.bat
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.nnabla-test
  docker/development/Dockerfile.nnabla-test-armhf
  docker/development/Dockerfile.nnabla-test-ppc64le
  include/nbla/function/istft.hpp
  include/nbla/function/stft.hpp
  include/nbla/function/utils/stft_istft.hpp
  python/src/nnabla/backward_function/istft.py
  python/src/nnabla/backward_function/stft.py
  python/src/nnabla/functions.py
  python/test/function/test_istft.py
  python/test/function/test_stft.py
  python/test_requirements.txt
  src/nbla/function/generic/istft.cpp
  src/nbla/function/generic/stft.cpp
Labels: release-note-op-layer

#1000 Support broadcast in instance norm kernel to improve performance
  python/benchmark/function/test_normalization_functions.py
  python/src/nnabla/backward_function/instance_normalization.py
  python/test/function/test_instance_normalization.py
  python/test/function/test_layer_normalization.py
Labels: release-note-op-layer

#1001 limit tensorflow version to 2.5.1
  python/src/nnabla/utils/converter/setup.py
Labels: release-note-format-converter

#1002 revise readthedocs document
  build-tools/code_generator/functions.yaml
  build-tools/code_generator/solvers.yaml
  python/src/nnabla/functions.py
  python/src/nnabla/normalization_functions.py
  python/src/nnabla/parametric_functions.py
Labels: release-note-doc

#1004 Prepare appropriate python-dev environment for test
  docker/development/Dockerfile.nnabla-test
  docker/development/Dockerfile.nnabla-test-ppc64le
Labels: release-note-ignore

#1005 fix multithread potential issue
  src/nbla/init.cpp.tmpl
Labels: release-note-bugfix

#1009 do not remove identity layer if it is not created by expend control
  python/src/nnabla/core/graph_def.py
  python/src/nnabla/utils/load.py
  python/test/core/test_bugfix_valid.py
Labels: release-note-bugfix

#1006 Remove the argument "output_mask" from Dropout
  .gitignore
  build-tools/code_generator/functions.yaml
  include/nbla/function/dropout.hpp
  include/nbla/function/utils/dropout_workaround.hpp
  include/nbla/variable.hpp
  python/setup.py
  python/src/nnabla/_dropout_workaround.pxd
  python/src/nnabla/_dropout_workaround.pyx
  python/src/nnabla/backward_function/dropout.py
  python/src/nnabla/functions.py
  python/test/function/test_dropout.py
  src/nbla/function/generic/dropout.cpp
  src/nbla/function/utils/dropout_workaround.cpp
Labels: release-note-bugfix

#1008 improve document for watch dog
  doc/python/tutorial/multi_device_training.rst
  docker/development/Dockerfile.build-armhf
  docker/development/Dockerfile.document
  tutorial/multi_device_training.ipynb
Labels: release-note-doc

#1010 Remove -U option from pip install in nnabla
  doc/build/build.md
  doc/build/quick_build_tools.md
  doc/locale/ja/LC_MESSAGES/python/file_format_converter/file_format_converter.po
Labels: release-note-ignore

#1013 Do not install test_requirements.txt when building armhf wheel
  docker/development/Dockerfile.build-armhf
Labels: release-note-ignore

#1012 Update QuantizeLinear&QuantizeLinear support status
  doc/python/file_format_converter/Function-Level_Support_Status.rst
Labels: release-note-doc

#1011 upgrade g++ from 4.9.2 to 6.5.0 and enable stdc++14
  .gitignore
  CMakeLists.txt
  docker/development/Dockerfile.android
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-armhf
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.nnabla-test
  docker/development/Dockerfile.nnabla-test-armhf
  docker/development/Dockerfile.nnabla-test-ppc64le
  examples/cpp/cpp_graph/CMakeLists.txt
  examples/cpp/mnist_collection/CMakeLists.txt
  examples/cpp/mnist_collection/GNUmakefile
  examples/cpp/mnist_collection/README.md
  examples/cpp/mnist_runtime/CMakeLists.txt
  examples/cpp/mnist_runtime/GNUmakefile
  examples/cpp/mnist_runtime/README.md
  examples/cpp/mnist_training/CMakeLists.txt
  examples/cpp/mnist_training/GNUmakefile
  examples/cpp/mnist_training/README.md
  python/setup.py
  src/nbla/CMakeLists.txt
  src/nbla_cli/CMakeLists.txt
  src/nbla_utils/CMakeLists.txt
Labels: release-note-build

#1014 Add breathe to doc dep requirements
  doc/requirements.txt
Labels: release-note-ignore
