Repository sony/nnabla, pull requests merged in 2021-04, with the labels that each got.

#846 fix nnp_graph load hang up
  python/src/nnabla/core/graph_def.py
Labels: release-note-bugfix

#851 fused binary operator
  include/nbla/function/utils/base_transform_binary.hpp
  python/benchmark/function/test_binary_operation.py
Labels: release-note-op-layer

#853 limit h5py version to 3.1.0
  python/requirements.txt
  python/setup.py
Labels: release-note-ignore

#854 Add stop_exhausted option for data_iterator
  python/src/nnabla/utils/data_iterator.py
  python/test/utils/test_data_iterator.py
Labels: release-note-utility

#855 Fix error of saving model and enable variable_batch_size.
  python/src/nnabla/core/variable_batch_size.py
Labels: release-note-bugfix

#856 fix the problem when save repeated float arguments
  python/src/nnabla/utils/save_function.py.tmpl
Labels: release-note-bugfix

#857 Make data_iterator_simple simpler
  python/src/nnabla/utils/data_iterator.py
Labels: release-note-bugfix

#859 Bug fix: Correct default arguments of F.norm_normalization
  python/src/nnabla/functions.py
Labels: release-note-bugfix

#858 Fix download failure on Windows
  build-tools/msvc/tools/build_libarchive.bat
  build-tools/msvc/tools/build_zlib.bat
  doc/build/build_cpp_utils_windows.md
  doc/build/build_windows.md
Labels: release-note-build

#860 set h5py version <= 3.1.0
  python/requirements.txt
  python/setup.py
Labels: release-note-ignore

#863 Add target of install converter.
  build-tools/make/build.mk
Labels: release-note-utility

#864 fix nnpload no variable name problem
  python/src/nnabla/utils/nnp_graph.py
  python/test/core/test_nnp_graph.py
Labels: release-note-utility

#862 L2-Norm initialization for weight normalization
  doc/python/api/parametric_function.rst
  python/src/nnabla/initializer.py
  python/src/nnabla/parametric_functions.py
  python/test/test_initializer.py
  python/test/test_parametric_functions.py
Labels: release-note-break-compat

#861 Searchsorted and Meshgrid implementation
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/meshgrid.hpp
  include/nbla/function/searchsorted.hpp
  python/src/nnabla/backward_function/meshgrid.py
  python/src/nnabla/backward_function/searchsorted.py
  python/src/nnabla/functions.py
  python/test/function/test_meshgrid.py
  python/test/function/test_searchsorted.py
  python/test/nbla_test_utils.py
  src/nbla/function/generic/meshgrid.cpp
  src/nbla/function/generic/searchsorted.cpp
Labels: release-note-op-layer

#865 support sequential
  doc/python/api.rst
  doc/python/api/sequential.rst
  python/src/nnabla/__init__.py
  python/src/nnabla/core/sequential.py
  python/test/core/test_sequential.py
Labels: release-note-core

#866 Fix load BytesIO failure.
  python/src/nnabla/utils/audio_utils/pydub_utils.py
  python/src/nnabla/utils/image_utils/backend_events/image_utils_backend.py
Labels: release-note-bugfix

#867 Fix problems
  python/src/nnabla/core/graph_def.py
Labels: release-note-bugfix

#868 Fix Conv1d of ONNX exporter and set the default opset to 11.
  python/src/nnabla/utils/converter/onnx/exporter.py
Labels: release-note-bugfix

#869 Enable the support of module for viewers
  python/src/nnabla/experimental/viewers.py
Labels: release-note-utility

#870 Fix RandomShift class initialization order issue
  include/nbla/function/random_shift.hpp
Labels: release-note-bugfix

#871 No grad context and converter
  doc/python/api/computation_graph.rst
  python/src/nnabla/__init__.py
  python/src/nnabla/_variable.pyx
  python/src/nnabla/experimental/graph_converters/__init__.py
  python/src/nnabla/experimental/graph_converters/no_grad.py
  python/src/nnabla/function.pyx.tmpl
  python/src/nnabla/parameter.py
  python/test/test_parameter.py
  python/test/utils/test_graph_converters/graph_converter_test_utils.py
  python/test/utils/test_graph_converters/test_no_grad.py
Labels: release-note-core

#872 Use urllib instead of requests
  docker/development/Dockerfile.nnabla-test-armhf
  docker/py37/Dockerfile.armhf
  python/requirements.txt
  python/setup.py
  python/src/nnabla/utils/cli/uploader.py
  python/src/nnabla/utils/data_source_loader.py
  python/src/nnabla/utils/download.py
Labels: release-note-utility

#875 fix format for random_shift.
  include/nbla/function/random_shift.hpp
Labels: release-note-ignore

#873 Modify SoftPlus to accept beta argument
  build-tools/code_generator/functions.yaml
  include/nbla/function/softplus.hpp
  python/src/nnabla/backward_function/softplus.py
  python/test/function/test_softplus.py
  src/nbla/function/generic/softplus.cpp
Labels: release-note-op-layer
