Repository sony/nnabla, pull requests merged in 2021-05, with the labels that each got.

#878 replace add_stylesheet with add_css_file
  doc/conf.py
Labels: release-note-ignore

#880 Update nnabla convert doc at 20210421
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-doc

#883 Fix recompute to check if data is cleared before backward without setup_recompute
  include/nbla/function.hpp
  python/test/test_graph.py
  src/nbla/computation_graph/variable.cpp
  src/nbla/function.cpp
Labels: release-note-bugfix
