Repository sony/nnabla, pull requests merged in 2021-09, with the labels that each got.

#960 fix CUDA version in README
  README.md
Labels: release-note-ignore

#962 Bugfix the higher-order gradient of gather_nd
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/scatter_nd.hpp
  python/src/nnabla/backward_function/gather_nd.py
  python/src/nnabla/backward_function/scatter_nd.py
  python/src/nnabla/functions.py
  python/test/function/test_gather_nd.py
  src/nbla/function/generic/scatter_nd.cpp
Labels: release-note-bugfix

#963 Add a wrapper of setenv for compatibility with Windows
  include/nbla/common.hpp
Labels: release-note-ignore

#964 Ease protobuf versions
  src/nbla_utils/parameters.cpp
Labels: release-note-build

#965 prompt user to install flatbuffers package
  python/src/nnabla/utils/converter/tflite/exporter.py
Labels: release-note-utility

#966 fix problem by ignore invalid text file
  build-tools/code_formatter/copyright_checker.py
Labels: release-note-build

#967 fix sample missing problem for slice iterator
  python/src/nnabla/utils/data_iterator.py
  python/test/utils/test_sliced_data_iterator.py
Labels: release-note-utility

#968 add extension and type_config arguments to create_communicator.
  python/src/nnabla/utils/communicator_util.py
Labels: release-note-utility

#969 Fix pillow save image with wrong array shape in grayscale mode.
  python/src/nnabla/utils/image_utils/backend_events/common.py
  python/src/nnabla/utils/image_utils/backend_events/pil_backend.py
Labels: release-note-utility
