Repository sony/nnabla, pull requests merged in 2021-11, with the labels that each got.

#981 fix remove_and_rewire causes set_variable disconnected issue
  python/src/nnabla/core/graph_def.py
  python/test/core/helper.py
  python/test/core/test_nnp_graph.py
Labels: release-note-bugfix

#982 eliminate code warning
  examples/cpp/cpp_graph/main.cpp
  examples/cpp/mnist_training/mnist_training.hpp
  include/nbla/lms/swap_in_out_scheduler.hpp
  src/nbla/function/generic/pad.cpp
  src/nbla/lms/swap_in_out_scheduler.cpp
  src/nbla/memory/virtual_caching_allocator.cpp
  src/nbla_cli/internal.cpp
  src/nbla_cli/nbla_dump.cpp
  src/nbla_cli/nbla_infer.cpp
  src/nbla_utils/data_iterator_npy.cpp
  src/nbla_utils/nnp_impl_dataset_npy.cpp
  src/nbla_utils/nnp_impl_monitor.cpp
  src/nbla_utils/nnp_network_expander.cpp
  src/nbla_utils/parameters.cpp
Labels: release-note-ignore

#983 Feature/20211014 pytest parallel exec
  build-tools/make/build.mk
  build-tools/msvc/test.bat
  python/pytest.ini
  python/test/core/test_module.py
  python/test/core/test_parameter_load_save.py
  python/test_requirements.txt
Labels: release-note-build

#985 feat: update image_utils for updated opencv-python package.
  python/src/nnabla/utils/image_utils/backend_events/common.py
  python/test/utils/test_image_utils.py
Labels: release-note-bugfix

#986 Feature/20211026 pep600 centos7
  build-tools/auditwheel-nnabla
  doc/python/install_on_linux.rst
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-ppc64le
Labels: release-note-build

#987 Skip test_warp_by_grid.py
  python/test/function/test_warp_by_grid.py
Labels: release-note-build

#993 Optimize CumProd/CumSum
  include/nbla/function/cumprod.hpp
  include/nbla/function/cumsum.hpp
  python/benchmark/function/test_cumprod.py
  python/test/function/refs.py
  python/test/function/test_cumprod.py
  python/test/function/test_cumsum.py
  src/nbla/function/generic/cumprod.cpp
Labels: release-note-op-layer

#992 support python3.9
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.nnabla-test
  docker/release/Dockerfile.py39
  python/src/nnabla/utils/converter/setup.py
Labels: release-note-build
