Repository sony/nnabla, pull requests merged in 2022-10, with the labels that each got.

#1114 correct index error in generate_cache_dir().
  python/test/utils/conftest.py
  python/test/utils/test_sliced_data_iterator.py
Labels: release-note-bugfix

#1116 Add callback APIs to doc
  CMakeLists.txt
  build-tools/make/build-with-docker.mk
  doc/python/api.rst
  doc/requirements.txt
  doc/requirements.txt.tmpl
  docker/development/Dockerfile.document
Labels: release-note-doc

#1117 fix version mismatch for libarchive.so
  docker/development/Dockerfile.nnabla-test
Labels: release-note-build

#1119 Added ca-certificates to Dockerfiles
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.nnabla-test
  docker/development/Dockerfile.nnabla-test-ppc64le
  docker/release/Dockerfile
  docker/runtime/Dockerfile
Labels: release-note-build

#1120 Not to all-reduce gradients of beta and gamma in sync BN
  .gitignore
  build-tools/code_generator/functions.yaml
  python/test/communicator/test_sync_batch_normalization.py
  src/nbla/function/generic/sync_batch_normalization.cpp
Labels: release-note-bugfix

#1121 fix:skip unnecessary download
  third_party/CMakeLists.txt
Labels: release-note-bugfix

#1122 Update nnabla converter document
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-doc

#1123 Create cache on each distributed node
  python/src/nnabla/utils/load.py
Labels: release-note-utility

#1124 fix crash problem of pipeline
  python/test/utils/test_sliced_data_iterator.py
Labels: release-note-bugfix
