Repository sony/nnabla, pull requests merged in 2022-12, with the labels that each got.

#1140 Fix git reset problem on creating nnabla wheel
  build-tools/make/build.mk
Labels: release-note-ignore

#1142 increate acceptable threshold for interpolate test on Windows
  python/test/function/test_interpolate.py
Labels: release-note-ignore

#1147 Remove deprecated API warning and compiler warning
  python/requirements.txt
  python/src/nnabla/_indexing.pyx
  python/src/nnabla/_variable.pyx
  python/src/nnabla/communicator.pyx
  python/src/nnabla/contrib/context.py
  python/src/nnabla/dtypes.py
  python/src/nnabla/ext_utils.py
  python/src/nnabla/function_bases.py.tmpl
  python/src/nnabla/functions.py
  python/src/nnabla/logger.py
  python/src/nnabla/parametric_functions.py
  python/src/nnabla/solver.pyx.tmpl
  python/src/nnabla/utils/cli/create_object_detection_dataset.py
  python/src/nnabla/utils/cli/utility.py
  python/src/nnabla/utils/converter/nnablart/save_variable_buffer.py
  python/src/nnabla/utils/converter/onnx/exporter.py
  python/src/nnabla/utils/converter/onnx/importer.py
  python/src/nnabla/utils/converter/tflite/exporter.py
  python/src/nnabla/utils/converter/tflite/quantized_converter.py
  python/src/nnabla/utils/get_file_handle.py
  python/src/nnabla/utils/image_utils/backend_events/pil_backend.py
  python/src/nnabla/utils/load.py
  python/src/nnabla/utils/signature_utils.py
  python/test/core/legacy_load.py
  python/test/function/test_batch_normalization.py
  python/test/function/test_bool_fill.py
  python/test/function/test_bool_gather.py
  python/test/function/test_bool_scatter.py
  python/test/function/test_broadcast.py
  python/test/function/test_categorical_cross_entropy.py
  python/test/function/test_confusion_matrix.py
  python/test/function/test_deformable_convolution.py
  python/test/function/test_gather.py
  python/test/function/test_softmax_cross_entropy.py
  python/test/function/test_top_n_error.py
  python/test/function/test_warp_by_flow.py
  python/test/test_parameter.py
  python/test/test_parametric_functions.py
  python/test/test_variable.py
  python/test/utils/test_data_source_loader.py
  python/test/utils/test_image_utils.py
  python/test/utils/test_sliced_data_iterator.py
  src/nbla/function/generic/celu.cpp
  src/nbla/function/generic/mean_subtraction.cpp
  src/nbla/function/generic/vat_noise.cpp
  src/nbla/function/generic/weight_standardization.cpp
Labels: release-note-ignore

#1146 Fix a potential bug in memory-release behavior in auto forward mode
  include/nbla/synced_array.hpp
  python/test/function/test_top_k_grad.py
  python/test/nbla_test_utils.py
  python/test/test_nd_array.py
  src/nbla/computation_graph/variable.cpp
  src/nbla/function/generic/identity.cpp
Labels: release-note-bugfix

#1143 add support for android-ndk-r25b
  build-tools/make/build-with-docker.mk
  build-tools/make/build.mk
  doc/build/build_android.md
  docker/development/Dockerfile.android
Labels: release-note-build

#1144 Add test corresponding the change of long long copy of nnabla-ext-cuda
  python/test/function/test_reduction.py
Labels: release-note-ignore

#1145 build python with pyenv
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-aarch64
  docker/development/Dockerfile.build-ppc64le
  docker/development/Dockerfile.document
  docker/development/Dockerfile.nnabla-test
  docker/development/Dockerfile.nnabla-test-aarch64
  docker/development/Dockerfile.nnabla-test-ppc64le
  docker/release/Dockerfile
  docker/release/Dockerfile.py39-aarch64
  docker/runtime/Dockerfile
  docker/tutorial/Dockerfile
Labels: release-note-build

#1150 Options to scale gradients and to keep dtype in allreduce callback
  include/nbla/communicator.hpp
  python/src/nnabla/communicator.pxd
  python/src/nnabla/communicator.pyx
  python/test/communicator/test_all_reduce_callback.py
  src/nbla/communicator.cpp
Labels: release-note-core

#1148 Minor fixes in build android document
  doc/build/build_android.md
  docker/development/Dockerfile.android
Labels: release-note-ignore

#1149 fix namespace packages for wheel to pass twine check
  python/setup.py
  python/src/nnabla/utils/converter/README.md
  python/src/nnabla/utils/converter/setup.py
  python/src/nnabla_ext/__init__.py
Labels: release-note-build
