Repository sony/nnabla, pull requests merged in 2022-09, with the labels that each got.

#1096 Add narrow function for NdArray
  include/nbla/array.hpp
  include/nbla/array/cpu_array.hpp
  include/nbla/array/cpu_dlpack_array.hpp
  include/nbla/array/dlpack_array.hpp
  include/nbla/array_registry.hpp
  include/nbla/memory/allocator.hpp
  include/nbla/nd_array.hpp
  include/nbla/synced_array.hpp
  python/src/nnabla/_nd_array.pxd
  python/src/nnabla/_nd_array.pyx
  python/test/test_nd_array.py
  src/nbla/array/array.cpp
  src/nbla/array/cpu_array.cpp
  src/nbla/array/cpu_dlpack_array.cpp
  src/nbla/array/dlpack_array.cpp
  src/nbla/array_registry.cpp
  src/nbla/memory/allocator.cpp
  src/nbla/nd_array.cpp
  src/nbla/synced_array.cpp
Labels: release-note-core

#1097 Error function (erf) implementation (CPU)
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/erf.hpp
  include/nbla/half.hpp
  python/src/nnabla/backward_function/erf.py
  python/test/function/test_erf.py
  src/nbla/function/generic/erf.cpp
  src/nbla/half.cpp
Labels: release-note-op-layer

#1098 Improve of recursively apply attribute to module
  python/src/nnabla/core/module.py
Labels: release-note-ignore

#1099 build android target with dynamic link
  build-tools/make/build.mk
  docker/development/Dockerfile.android
  src/nbla_utils/CMakeLists.txt
Labels: release-note-build

#1100 restore the CL-initializer in legacy_nnp_graph.py to graph_def.py
  python/src/nnabla/core/graph_def.py
  python/test/core/test_nnp_graph.py
Labels: release-note-format-converter

#1101 add comment on the use of SingletonManager::clear()
  examples/cpp/cpp_graph/main.cpp
  examples/cpp/mnist_runtime/mnist_runtime.cpp
Labels: release-note-ignore

#1102 Fix issues in ONNX importer
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-format-converter

#1103 Add GlobalMaxPool, RandomNormal, RandomUniform support to ONNX importer
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-format-converter

#1104 fix dataset name for deeplabv3plus.
  doc/locale/ja/LC_MESSAGES/python/api/models/semantic_segmentation.po
  python/src/nnabla/models/semantic_segmentation/deeplabv3plus.py
Labels: release-note-ignore

#1105 add code to allow unlink variable
  python/src/nnabla/utils/nnp_graph.py
Labels: release-note-bugfix

#1106 Remove flatbuffer build
  docker/release/Dockerfile
Labels: release-note-ignore

#1108 Fix a bug in OnnxImporter.get_func_input_shape
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-ignore

#1109 fix numpy indice error due to numpy version update
  python/test/function/refs.py
  python/test/function/test_scatter_nd.py
  python/test/function/test_slice.py
Labels: release-note-bugfix

#1110 add tensorboard version dependency of file format converter
  python/src/nnabla/utils/converter/setup.py
Labels: release-note-build

#1111 Add TopK support to ONNX importer
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/top_k_data.hpp
  include/nbla/utils/top_k.hpp
  python/src/nnabla/utils/converter/onnx/importer.py
  python/test/function/test_top_k_data.py
  src/nbla/function/generic/top_k_data.cpp
  src/nbla/function/generic/top_k_grad.cpp
Labels: release-note-format-converter

#1112 fix install_requires
  python/src/nnabla/utils/converter/setup.py
Labels: release-note-ignore

#1113 implement drop_last option for slice
  python/src/nnabla/utils/data_iterator.py
  python/test/utils/test_data_iterator.py
  python/test/utils/test_sliced_data_iterator.py
Labels: release-note-bugfix
