Repository sony/nnabla, pull requests merged in 2022-03, with the labels that each got.

#1032 restrict condition with dst for communicator reduce
  python/test/communicator/test_comm_reduce.py
Labels: release-note-core

#1033 force epoch begin and end callback be called from main thread
  python/src/nnabla/utils/data_iterator.py
  python/test/utils/test_data_iterator.py
Labels: release-note-utility

#1035 Add Pad to FusedConvolution
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/functions.yaml
  include/nbla/function/fused_convolution.hpp
  python/test/function/test_fused_convolution.py
  src/nbla/function/generic/fused_convolution.cpp
Labels: release-note-op-layer

#1034 build with VS2019
  build-tools/msvc/build_cpplib.bat
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/test_nbla.bat
  build-tools/msvc/tools/build_protobuf.bat
  build-tools/msvc/tools/env.bat
  build-tools/msvc/tools/get_liblz4.bat
  build-tools/msvc/tools/get_libzstd.bat
  build-tools/msvc/tools/python_env.bat
Labels: release-note-build

#1036 upgrade tensorflow from 2.5.1 to 2.7.x
  python/src/nnabla/utils/converter/setup.py
Labels: release-note-build

#1038 Fused weight decay into Solver update / Fix SgdW / Add Lamb solver
  build-tools/code_generator/solver_types.yaml
  build-tools/code_generator/solvers.yaml
  build-tools/make/build.mk
  build-tools/make/options.mk
  doc/python/api/solver.rst
  include/nbla/solver.hpp
  include/nbla/solver/adabelief.hpp
  include/nbla/solver/adamw.hpp
  include/nbla/solver/lamb.hpp
  include/nbla/solver/lars.hpp
  include/nbla/solver/sgdw.hpp
  python/src/nnabla/solver.pxd.tmpl
  python/src/nnabla/solver.pyx.tmpl
  python/test/solver/solver_test_utils.py
  python/test/solver/test_adabelief.py
  python/test/solver/test_adabound.py
  python/test/solver/test_adadelta.py
  python/test/solver/test_adagrad.py
  python/test/solver/test_adam.py
  python/test/solver/test_adamax.py
  python/test/solver/test_adamw.py
  python/test/solver/test_amsbound.py
  python/test/solver/test_amsgrad.py
  python/test/solver/test_lamb.py
  python/test/solver/test_lars.py
  python/test/solver/test_momentum.py
  python/test/solver/test_nesterov.py
  python/test/solver/test_rmsprop.py
  python/test/solver/test_rmsprop_graves.py
  python/test/solver/test_sgd.py
  python/test/solver/test_sgdw.py
  src/nbla/solver.cpp
  src/nbla/solver/generic/adabelief.cpp
  src/nbla/solver/generic/adamw.cpp
  src/nbla/solver/generic/lamb.cpp
  src/nbla/solver/generic/lars.cpp
  src/nbla/solver/generic/sgdw.cpp
Labels: release-note-bugfix, release-note-core

#1040 Improve docker entrypoint set
  docker/release/.entrypoint.sh
Labels: release-note-ignore

#1039 arm64 support
  build-tools/make/build.mk
  docker/development/Dockerfile.build-aarch64
  docker/development/Dockerfile.nnabla-test-aarch64
  docker/release/Dockerfile.py39-aarch64
  python/requirements.txt
  python/setup.py
  python/test/nbla_test_utils.py
Labels: release-note-build

#1041 Add batch cholesky function
  build-tools/code_generator/api_levels.yaml
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/functions.yaml
  doc/python/api/function.rst
  include/nbla/function/batch_cholesky.hpp
  python/src/nnabla/backward_function/batch_cholesky.py
  python/test/function/test_batch_cholesky.py
  src/nbla/function/generic/batch_cholesky.cpp
Labels: release-note-op-layer
