Repository sony/nnabla, pull requests merged in 2022-04, with the labels that each got.

#1042 Improve bnfolding converter
  python/src/nnabla/experimental/graph_converters/batch_normalization_folding.py
  python/test/utils/test_graph_converters/ref_graphs/helper.py
  python/test/utils/test_graph_converters/ref_graphs/resnets.py
  python/test/utils/test_graph_converters/test_batch_normalization_folding.py
Labels: release-note-format-converter

#1044 remove unnecessary dependency of onnx test
  python/test/utils/conversion/HOW_TO_UPDATE_REPORT.md
  python/test/utils/conversion/__init__.py
  python/test/utils/conversion/conftest.py
  python/test/utils/conversion/gen_report.py
  python/test/utils/conversion/onnx_test_report.rst.tmpl
  python/test/utils/conversion/test_conversion.py
Labels: release-note-ignore

#1045 make varaible's slice consistent between function call and build-in o…
  python/src/nnabla/functions.py
  python/test/test_indexing.py
Labels: release-note-bugfix

#1046 feat: extend onnx importer opset12
  python/src/nnabla/utils/converter/onnx/importer.py
Labels: release-note-format-converter

#1047 Fix param dtype translate in python test.
  python/test/nbla_test_utils.py
Labels: release-note-bugfix

#1048 Change aarch64 manylinux tag
  build-tools/auditwheel-nnabla
Labels: release-note-ignore

#1052 Add a benchmark script for Softmax
  python/benchmark/function/test_binary_operation.py
  python/benchmark/function/test_softmax.py
Labels: release-note-ignore

#1054 Increase cppcheck cpu.
  .rocro.yml
Labels: release-note-ignore

#1053 Add the support of loading parameter from buffer
  include/nbla_utils/parameters.hpp
  src/nbla_utils/parameters.cpp
  src/nbla_utils/test/test_load_save_parameters.cpp
Labels: release-note-cpp-api

#1049 fix segmetation load bug
  python/src/nnabla/models/semantic_segmentation/base.py
  python/src/nnabla/models/semantic_segmentation/deeplabv3plus.py
Labels: release-note-bugfix

#1051 fix yolov2 load error
  python/src/nnabla/models/object_detection/base.py
  python/src/nnabla/models/object_detection/yolov2.py
Labels: release-note-bugfix

#1056 implement version-down converter of nnp to nnp
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/converter/commands.py
  python/src/nnabla/utils/converter/nnabla/__init__.py
  python/src/nnabla/utils/converter/utils.py
  python/test/utils/conversion/nntxt.py
  python/test/utils/conversion/test_nnp_to_nnp_with_version.py
Labels: release-note-format-converter

#1057 Update nnabla convert doc at 20220411
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-doc

#1058 add a new GraphConverter to support weight pruning
  doc/python/api/experimentals/graph_converters.rst
  python/src/nnabla/experimental/graph_converters/__init__.py
  python/src/nnabla/experimental/graph_converters/prune.py
  python/test/utils/test_graph_converters/ref_graphs/resnets.py
  python/test/utils/test_graph_converters/test_pruning.py
Labels: release-note-utility

#1060 Fix flatc build issue
  docker/release/Dockerfile
  docker/release/Dockerfile.py39-aarch64
Labels: release-note-build

#1061 fix import error after remove __init__.py
  python/test/utils/conversion/__init__.py
Labels: release-note-ignore

#1062 support save parameters to buffer
  include/nbla_utils/parameters.hpp
  src/nbla_utils/parameters.cpp
  src/nbla_utils/test/test_load_save_parameters.cpp
Labels: release-note-cpp-api
