Repository sony/nnabla, pull requests merged in 2022-01, with the labels that each got.

#1015 Make Dockerfile.document depends on doc/requirements.txt
  doc/requirements.txt
  docker/development/Dockerfile.document
Labels: release-note-build

#1017 install distutils for py39
  docker/release/Dockerfile.py39
Labels: release-note-ignore

#1020 make corresponding modification for the files in reconstruction directories
  doc/locale/ja/LC_MESSAGES/python/pip_installation.po
  doc/python/pip_installation.rst
  doc/python/tutorial/multi_device_training.rst
  examples/cpp/mnist_runtime/README.md
  examples/cpp/mnist_runtime/save_nnp_classification.py
  examples/cpp/mnist_training/create_initialized_model.py
  examples/cpp/nbla_train/create_initialized_model.py
  examples/cpp/nbla_train/create_mnist_cache.py
  python/test/cpp/test_mnist_runtime.py
  tutorial/multi_device_training.ipynb
Labels: release-note-examples

#1019 Update nnabla convert doc at 20211224
  doc/python/file_format_converter/Function-Level_Support_Status.rst
  doc/python/file_format_converter/Model_Support_Status.rst
Labels: release-note-ignore

#1018 Fix illegal access in deformable convolution
  src/nbla/function/generic/deformable_convolution.cpp
Labels: release-note-bugfix

#1023 Fix FusedBN not to fall back to cpu implementation always
  include/nbla/function/fused_batch_normalization.hpp
  src/nbla/function/generic/fused_batch_normalization.cpp
Labels: release-note-bugfix
