Repository sony/nnabla, pull requests merged in 2022-05, with the labels that each got.

#1065 add warning if parameter file is not supported
  python/src/nnabla/utils/get_file_handle.py
Labels: release-note-utility

#1066 save no_image_normalization in executor if exist
  python/src/nnabla/utils/save.py
Labels: release-note-bugfix

#1067 fix inf serialization bug
  python/src/nnabla/function.pyx.tmpl
  python/test/function/test_constant.py
Labels: release-note-bugfix

#1068 Build flatc from latest upstream release
  docker/release/Dockerfile
Labels: release-note-build

#1069 Derived class from Module wraps all methods for parameter scope
  python/src/nnabla/core/module.py
  python/test/core/test_module.py
Labels: release-note-bugfix

#1072 use numpy 1.20.0 and later
  build-tools/msvc/tools/python_env.bat
  docker/development/Dockerfile.document
  docker/development/Dockerfile.nnabla-test-aarch64
  python/requirements.txt
  python/setup.py
Labels: release-note-build
