Repository sony/nnabla, pull requests merged in 2022-08, with the labels that each got.

#1087 Update scipy I/F from 1.9.x
  python/test/function/test_istft.py
  python/test/function/test_stft.py
Labels: release-note-build

#1088 fix proto to info.proto in load.py
  python/src/nnabla/utils/load.py
Labels: release-note-bugfix

#1089 allow selection of python to be used when running build_cpplib.bat
  build-tools/msvc/build_cpplib.bat
  build-tools/msvc/tools/env.bat
Labels: release-note-build

#1090 include cuda/cudnn libraries in wheel
  build-tools/auditwheel-nnabla
Labels: release-note-build

#1091 Add benchmark for F.transpose()
  python/benchmark/function/test_transpose.py
Labels: release-note-build

#1093 Update supporting CUDA versions
  doc/python/pip_installation_cuda.rst
Labels: release-note-ignore

#1094 modify nnabla code format to support new autopep8
  python/src/nnabla/core/graph_def.py
  python/src/nnabla/monitor.py
  python/src/nnabla/utils/cli/convert.py
  python/src/nnabla/utils/converter/nnablart/nnb.py
  python/src/nnabla/utils/data_source_implements.py
  python/src/nnabla/utils/data_source_loader.py
  python/test/core/legacy_load.py
  python/test/core/legacy_network.py
  python/test/function/refs.py
  python/test/function/test_fused_convolution.py
  python/test/function/test_inq_affine.py
  python/test/function/test_inq_convolution.py
  python/test/function/test_istft.py
  python/test/function/test_random_crop.py
  python/test/test_graph.py
Labels: release-note-ignore

#1095 update version dependency of file format converter
  python/src/nnabla/utils/converter/setup.py
Labels: release-note-format-converter
