Repository sony/nnabla, pull requests merged in 2023-02, with the labels that each got.

#1165 update MacOS document
  doc/build/build_macos.md
  doc/python/install_on_macos.rst
Labels: release-note-doc

#1166 Fix executing profile on CPU environment.
  python/src/nnabla/__main__.py
  python/src/nnabla/utils/cli/profile.py
Labels: release-note-bugfix

#1167 fix alllib wheel dependency in cuda11.6
  build-tools/auditwheel-nnabla
Labels: release-note-build

#1168 update bibtex and supported features
  README.md
Labels: release-note-doc

#1169 Check consistency among memory layouts in SyncBatchNormalization
  python/test/communicator/test_sync_batch_normalization.py
Labels: release-note-bugfix
